/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrieSearch_Lite */

#ifndef _Included_edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrieSearch_Lite
#define _Included_edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrieSearch_Lite
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrieSearch_Lite_searchThread */

#ifndef _Included_edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrieSearch_Lite_searchThread
#define _Included_edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrieSearch_Lite_searchThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrieSearch_Lite_searchThread
 * Method:    search
 * Signature: ([CI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrieSearch_1Lite_00024searchThread_search
  (JNIEnv *, jobject, jcharArray, jint);

#ifdef __cplusplus
}
#endif
#endif
