/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_Lite */

#ifndef _Included_edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_Lite
#define _Included_edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_Lite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_Lite
 * Method:    addSeq
 * Signature: ([CI)V
 */
JNIEXPORT void JNICALL Java_edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_1Lite_addSeq
  (JNIEnv *, jobject, jcharArray, jint);

/*
 * Class:     edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_Lite
 * Method:    newSuffixTrie
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_1Lite_newSuffixTrie
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_Lite
 * Method:    getInitializationStatus
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_1Lite_getInitializationStatus
  (JNIEnv *, jobject);

/*
 * Class:     edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_Lite
 * Method:    addRoot
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_1Lite_addRoot
  (JNIEnv *, jobject, jchar);

/*
 * Class:     edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_Lite
 * Method:    getTotalNodes
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_1Lite_getTotalNodes
  (JNIEnv *, jobject);

/*
 * Class:     edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_Lite
 * Method:    begingMemoryCounter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_1Lite_begingMemoryCounter
  (JNIEnv *, jobject);

/*
 * Class:     edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_Lite
 * Method:    endMemoryCounter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_1Lite_endMemoryCounter
  (JNIEnv *, jobject);

/*
 * Class:     edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_Lite
 * Method:    printMemoryStatus
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_1Lite_printMemoryStatus
  (JNIEnv *, jobject);

/*
 * Class:     edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_Lite
 * Method:    setNodeCounter
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_1Lite_setNodeCounter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_Lite
 * Method:    setNode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_1Lite_setNode
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_Lite
 * Method:    writeSuffixTrie
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_1Lite_writeSuffixTrie
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_Lite_SuffixTrie_LiteHolder */

#ifndef _Included_edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_Lite_SuffixTrie_LiteHolder
#define _Included_edu_uiowa_icts_ray_jnisuffixtrie_SuffixTrie_Lite_SuffixTrie_LiteHolder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
