/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_uiowa_icts_ray_entry_Main */

#ifndef _Included_edu_uiowa_icts_ray_entry_Main
#define _Included_edu_uiowa_icts_ray_entry_Main
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_uiowa_icts_ray_entry_Main_distribution
#define edu_uiowa_icts_ray_entry_Main_distribution 1L
/*
 * Class:     edu_uiowa_icts_ray_entry_Main
 * Method:    nativeGetIntArray
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_edu_uiowa_icts_ray_entry_Main_nativeGetIntArray
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
