package edu.uiowa.icts.safeseed.controller;

import java.util.HashMap;
import java.util.Map;

import java.util.concurrent.ConcurrentHashMap;
import edu.uiowa.icts.spring.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.ModelAttribute;

import edu.uiowa.icts.safeseed.dao.*;
import edu.uiowa.icts.safeseed.domain.SiteContent;

/* Generated by Protogen
 *
 *
 *
 */

public abstract class AbstractSafeseedController {




	public static Map<String,String> siteContentMap = null;

	/*********** safeseedDaoService ****************/
	protected SafeseedDaoService safeseedDaoService; 

	@Autowired 
	public void setSafeseedDaoService(SafeseedDaoService safeseedDaoService)
	{
		this.safeseedDaoService = safeseedDaoService;
	}

	@ModelAttribute( value="username")
	public String getUsername() {
		return SecurityContextHolder.getContext().getAuthentication().getName();
	}

	@ModelAttribute( value="siteContentMap")
	public Map<String,String> getSiteContentMap(){
		if(siteContentMap ==null){
			populate();
		}
		return siteContentMap;

	}


	public void populate(){
		siteContentMap = new ConcurrentHashMap<String,String>();
		for(SiteContent sc : safeseedDaoService.getSiteContentService().list()){

			siteContentMap.put(sc.getLabel(), sc.getContent());
		}



	}




}
