package edu.uiowa.icts.safeseed.controller;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import edu.uiowa.icts.safeseed.dao.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

/* Generated by Protogen
 *
Fri Mar 04 07:04:26 CST 2011 *
*/

@Controller
@RequestMapping("/safeseed/audit/*")
public class AuditController extends AbstractSafeseedController {


    private static final Log log =LogFactory.getLog(AuditController.class);

    @RequestMapping(value = "list.html", method = RequestMethod.GET)
    public ModelAndView list()
    {
        log.debug("in list method for Audit");
        ModelMap model = new ModelMap();
        model.addAttribute("auditList",safeseedDaoService.getAuditService().list());
        return new ModelAndView("/safeseed/audit/list",model);
    }

    @RequestMapping(value = "add.html", method = RequestMethod.GET)
    public ModelAndView add()
    {
        log.debug("in add method for Audit");
        ModelMap model = new ModelMap();
        Audit audit = new Audit();
        model.addAttribute("audit",audit);
        return new ModelAndView("/safeseed/audit/edit",model);
    }

    @RequestMapping(value = "edit.html", method = RequestMethod.GET)
    public ModelAndView edit(@RequestParam("auditId") Integer auditId)
    {
        log.debug("in edit method for Audit");
        ModelMap model = new ModelMap();
        Audit audit = safeseedDaoService.getAuditService().findById(auditId);
        model.addAttribute("audit",audit);
        return new ModelAndView("/safeseed/audit/edit",model);
    }

    @RequestMapping(value = "show.html", method = RequestMethod.GET)
    public ModelAndView show(@RequestParam("auditId") Integer auditId)
    {
        log.debug("in show method for Audit");
        ModelMap model = new ModelMap();
        Audit audit = safeseedDaoService.getAuditService().findById(auditId);
        model.addAttribute("audit",audit);
        return new ModelAndView("/safeseed/audit/show",model);
    }

    @RequestMapping(value = "save.html", method = RequestMethod.POST)
    public String save(@ModelAttribute("audit") Audit audit)
    {
        log.debug("in save method for Audit");
        safeseedDaoService.getAuditService().saveOrUpdate(audit);
        return "redirect:/safeseed/audit/list.html";
    }

    @RequestMapping(value = "delete.html", method = RequestMethod.GET)
    public String delete(@RequestParam("auditId") Integer auditId)
    {
        log.debug("in delete method for Audit");
        Audit audit = safeseedDaoService.getAuditService().findById(auditId);
        safeseedDaoService.getAuditService().delete(audit);
        return "redirect:/safeseed/audit/list.html";
    }
}