package edu.uiowa.icts.safeseed.controller;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import edu.uiowa.icts.safeseed.dao.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

/* Generated by Protogen
 *
Fri Mar 04 07:04:26 CST 2011 *
*/

@Controller
@RequestMapping("/safeseed/collection/*")
public class CollectionController extends AbstractSafeseedController {


    private static final Log log =LogFactory.getLog(CollectionController.class);

    @RequestMapping(value = "list.html", method = RequestMethod.GET)
    public ModelAndView list()
    {
        log.debug("in list method for Collection");
        ModelMap model = new ModelMap();
        model.addAttribute("collectionList",safeseedDaoService.getCollectionService().list());
        return new ModelAndView("/safeseed/collection/list",model);
    }

    @RequestMapping(value = "add.html", method = RequestMethod.GET)
    public ModelAndView add()
    {
        log.debug("in add method for Collection");
        ModelMap model = new ModelMap();
        Collection collection = new Collection();
        model.addAttribute("collection",collection);
        model.addAttribute("personList",safeseedDaoService.getPersonService().list());
        model.addAttribute("seqList",safeseedDaoService.getSeqService().list());
        return new ModelAndView("/safeseed/collection/edit",model);
    }

    @RequestMapping(value = "edit.html", method = RequestMethod.GET)
    public ModelAndView edit(@RequestParam("personId") int personId, @RequestParam("seqId") int seqId)
    {
        log.debug("in edit method for Collection");
        ModelMap model = new ModelMap();
        CollectionId collectionId = new CollectionId();
        collectionId.setPersonId(personId);
        collectionId.setSeqId(seqId);
        model.addAttribute("personList",safeseedDaoService.getPersonService().list());
        model.addAttribute("seqList",safeseedDaoService.getSeqService().list());
        Collection collection = safeseedDaoService.getCollectionService().findById(collectionId);
        model.addAttribute("collection",collection);
        return new ModelAndView("/safeseed/collection/edit",model);
    }

    @RequestMapping(value = "show.html", method = RequestMethod.GET)
    public ModelAndView show(@RequestParam("personId") int personId, @RequestParam("seqId") int seqId)
    {
        log.debug("in show method for Collection");
        ModelMap model = new ModelMap();
        CollectionId collectionId = new CollectionId();
        collectionId.setPersonId(personId);
        collectionId.setSeqId(seqId);
        Collection collection = safeseedDaoService.getCollectionService().findById(collectionId);
        model.addAttribute("collection",collection);
        return new ModelAndView("/safeseed/collection/show",model);
    }

    @RequestMapping(value = "save.html", method = RequestMethod.POST)
    public String save(@RequestParam("person.personId") Integer personId, @RequestParam("seq.seqId") Integer seqId, @ModelAttribute("collection") Collection collection)
    {
        log.debug("in save method for Collection");
        CollectionId collectionId = new CollectionId();
        collectionId.setPersonId(personId);
        collectionId.setSeqId(seqId);
            collection.setId( collectionId);
        safeseedDaoService.getCollectionService().saveOrUpdate(collection);
        return "redirect:/safeseed/collection/list.html";
    }

    @RequestMapping(value = "delete.html", method = RequestMethod.GET)
    public String delete(@RequestParam("personId") int personId, @RequestParam("seqId") int seqId)
    {
        log.debug("in delete method for Collection");
        CollectionId collectionId = new CollectionId();
        collectionId.setPersonId(personId);
        collectionId.setSeqId(seqId);
        Collection collection = safeseedDaoService.getCollectionService().findById(collectionId);
        safeseedDaoService.getCollectionService().delete(collection);
        return "redirect:/safeseed/collection/list.html";
    }
}