package edu.uiowa.icts.safeseed.controller;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import edu.uiowa.icts.safeseed.dao.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

/* Generated by Protogen
 *
Fri Mar 04 07:04:26 CST 2011 *
*/

@Controller
@RequestMapping("/safeseed/frag/*")
public class FragController extends AbstractSafeseedController {


    private static final Log log =LogFactory.getLog(FragController.class);

    @RequestMapping(value = "list.html", method = RequestMethod.GET)
    public ModelAndView list()
    {
        log.debug("in list method for Frag");
        ModelMap model = new ModelMap();
        model.addAttribute("fragList",safeseedDaoService.getFragService().list());
        return new ModelAndView("/safeseed/frag/list",model);
    }

    @RequestMapping(value = "add.html", method = RequestMethod.GET)
    public ModelAndView add()
    {
        log.debug("in add method for Frag");
        ModelMap model = new ModelMap();
        Frag frag = new Frag();
        model.addAttribute("frag",frag);
        model.addAttribute("seqFragList",safeseedDaoService.getSeqFragService().list());
        return new ModelAndView("/safeseed/frag/edit",model);
    }

    @RequestMapping(value = "edit.html", method = RequestMethod.GET)
    public ModelAndView edit(@RequestParam("fragId") Integer fragId)
    {
        log.debug("in edit method for Frag");
        ModelMap model = new ModelMap();
        model.addAttribute("seqFragList",safeseedDaoService.getSeqFragService().list());
        Frag frag = safeseedDaoService.getFragService().findById(fragId);
        model.addAttribute("frag",frag);
        return new ModelAndView("/safeseed/frag/edit",model);
    }

    @RequestMapping(value = "show.html", method = RequestMethod.GET)
    public ModelAndView show(@RequestParam("fragId") Integer fragId)
    {
        log.debug("in show method for Frag");
        ModelMap model = new ModelMap();
        Frag frag = safeseedDaoService.getFragService().findById(fragId);
        model.addAttribute("frag",frag);
        return new ModelAndView("/safeseed/frag/show",model);
    }

    @RequestMapping(value = "save.html", method = RequestMethod.POST)
    public String save(@RequestParam("seqFrag.seqFragId") Integer seqFragId, @ModelAttribute("frag") Frag frag)
    {
        log.debug("in save method for Frag");
        frag.setSeqFrag(safeseedDaoService.getSeqFragService().findById(seqFragId));
        safeseedDaoService.getFragService().saveOrUpdate(frag);
        return "redirect:/safeseed/frag/list.html";
    }

    @RequestMapping(value = "delete.html", method = RequestMethod.GET)
    public String delete(@RequestParam("fragId") Integer fragId)
    {
        log.debug("in delete method for Frag");
        Frag frag = safeseedDaoService.getFragService().findById(fragId);
        safeseedDaoService.getFragService().delete(frag);
        return "redirect:/safeseed/frag/list.html";
    }
    

}
