package edu.uiowa.icts.safeseed.controller;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import edu.uiowa.icts.safeseed.dao.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

/* Generated by Protogen
 *
Fri Mar 04 07:04:26 CST 2011 *
*/

@Controller
@RequestMapping("/safeseed/globalfrag/*")
public class GlobalFragController extends AbstractSafeseedController {


    private static final Log log =LogFactory.getLog(GlobalFragController.class);

    @RequestMapping(value = "list.html", method = RequestMethod.GET)
    public ModelAndView list()
    {
        log.debug("in list method for GlobalFrag");
        ModelMap model = new ModelMap();
        model.addAttribute("globalFragList",safeseedDaoService.getGlobalFragService().list());
        return new ModelAndView("/safeseed/globalfrag/list",model);
    }

    @RequestMapping(value = "add.html", method = RequestMethod.GET)
    public ModelAndView add()
    {
        log.debug("in add method for GlobalFrag");
        ModelMap model = new ModelMap();
        GlobalFrag globalFrag = new GlobalFrag();
        model.addAttribute("globalFrag",globalFrag);
        model.addAttribute("globalSeqFragList",safeseedDaoService.getGlobalSeqFragService().list());
        return new ModelAndView("/safeseed/globalfrag/edit",model);
    }

    @RequestMapping(value = "edit.html", method = RequestMethod.GET)
    public ModelAndView edit(@RequestParam("globalFragId") Integer globalFragId)
    {
        log.debug("in edit method for GlobalFrag");
        ModelMap model = new ModelMap();
        model.addAttribute("globalSeqFragList",safeseedDaoService.getGlobalSeqFragService().list());
        GlobalFrag globalFrag = safeseedDaoService.getGlobalFragService().findById(globalFragId);
        model.addAttribute("globalFrag",globalFrag);
        return new ModelAndView("/safeseed/globalfrag/edit",model);
    }

    @RequestMapping(value = "show.html", method = RequestMethod.GET)
    public ModelAndView show(@RequestParam("globalFragId") Integer globalFragId)
    {
        log.debug("in show method for GlobalFrag");
        ModelMap model = new ModelMap();
        GlobalFrag globalFrag = safeseedDaoService.getGlobalFragService().findById(globalFragId);
        model.addAttribute("globalFrag",globalFrag);
        return new ModelAndView("/safeseed/globalfrag/show",model);
    }

    @RequestMapping(value = "save.html", method = RequestMethod.POST)
    public String save(@RequestParam("globalSeqFrag.globalSeqFrag") Integer globalSeqFrag, @ModelAttribute("globalFrag") GlobalFrag globalFrag)
    {
        log.debug("in save method for GlobalFrag");
        globalFrag.setGlobalSeqFrag(safeseedDaoService.getGlobalSeqFragService().findById(globalSeqFrag));
        safeseedDaoService.getGlobalFragService().saveOrUpdate(globalFrag);
        return "redirect:/safeseed/globalfrag/list.html";
    }

    @RequestMapping(value = "delete.html", method = RequestMethod.GET)
    public String delete(@RequestParam("globalFragId") Integer globalFragId)
    {
        log.debug("in delete method for GlobalFrag");
        GlobalFrag globalFrag = safeseedDaoService.getGlobalFragService().findById(globalFragId);
        safeseedDaoService.getGlobalFragService().delete(globalFrag);
        return "redirect:/safeseed/globalfrag/list.html";
    }
    
}
