package edu.uiowa.icts.safeseed.controller;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import edu.uiowa.icts.safeseed.dao.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

/* Generated by Protogen
 *
Fri Mar 04 07:04:26 CST 2011 *
*/

@Controller
@RequestMapping("/safeseed/globalhistory/*")
public class GlobalHistoryController extends AbstractSafeseedController {


    private static final Log log =LogFactory.getLog(GlobalHistoryController.class);

    @RequestMapping(value = "list.html", method = RequestMethod.GET)
    public ModelAndView list()
    {
        log.debug("in list method for GlobalHistory");
        ModelMap model = new ModelMap();
        model.addAttribute("globalHistoryList",safeseedDaoService.getGlobalHistoryService().list());
        return new ModelAndView("/safeseed/globalhistory/list",model);
    }

    @RequestMapping(value = "add.html", method = RequestMethod.GET)
    public ModelAndView add()
    {
        log.debug("in add method for GlobalHistory");
        ModelMap model = new ModelMap();
        GlobalHistory globalHistory = new GlobalHistory();
        model.addAttribute("globalHistory",globalHistory);
        model.addAttribute("globalSeqFragList",safeseedDaoService.getGlobalSeqFragService().list());
        model.addAttribute("personList",safeseedDaoService.getPersonService().list());
        return new ModelAndView("/safeseed/globalhistory/edit",model);
    }

    @RequestMapping(value = "edit.html", method = RequestMethod.GET)
    public ModelAndView edit(@RequestParam("globalHistoryId") Integer globalHistoryId)
    {
        log.debug("in edit method for GlobalHistory");
        ModelMap model = new ModelMap();
        model.addAttribute("globalSeqFragList",safeseedDaoService.getGlobalSeqFragService().list());
        model.addAttribute("personList",safeseedDaoService.getPersonService().list());
        GlobalHistory globalHistory = safeseedDaoService.getGlobalHistoryService().findById(globalHistoryId);
        model.addAttribute("globalHistory",globalHistory);
        return new ModelAndView("/safeseed/globalhistory/edit",model);
    }

    @RequestMapping(value = "show.html", method = RequestMethod.GET)
    public ModelAndView show(@RequestParam("globalHistoryId") Integer globalHistoryId)
    {
        log.debug("in show method for GlobalHistory");
        ModelMap model = new ModelMap();
        GlobalHistory globalHistory = safeseedDaoService.getGlobalHistoryService().findById(globalHistoryId);
        model.addAttribute("globalHistory",globalHistory);
        return new ModelAndView("/safeseed/globalhistory/show",model);
    }

    @RequestMapping(value = "save.html", method = RequestMethod.POST)
    public String save(@RequestParam("globalSeqFrag.globalSeqFrag") Integer globalSeqFrag, @RequestParam("person.personId") Integer personId, @ModelAttribute("globalHistory") GlobalHistory globalHistory)
    {
        log.debug("in save method for GlobalHistory");
        globalHistory.setGlobalSeqFrag(safeseedDaoService.getGlobalSeqFragService().findById(globalSeqFrag));
        globalHistory.setPerson(safeseedDaoService.getPersonService().findById(personId));
        safeseedDaoService.getGlobalHistoryService().saveOrUpdate(globalHistory);
        return "redirect:/safeseed/globalhistory/list.html";
    }

    @RequestMapping(value = "delete.html", method = RequestMethod.GET)
    public String delete(@RequestParam("globalHistoryId") Integer globalHistoryId)
    {
        log.debug("in delete method for GlobalHistory");
        GlobalHistory globalHistory = safeseedDaoService.getGlobalHistoryService().findById(globalHistoryId);
        safeseedDaoService.getGlobalHistoryService().delete(globalHistory);
        return "redirect:/safeseed/globalhistory/list.html";
    }

}
