package edu.uiowa.icts.safeseed.controller;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import edu.uiowa.icts.safeseed.dao.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

/* Generated by Protogen
 *
Fri Mar 04 07:04:26 CST 2011 *
*/

@Controller
@RequestMapping("/safeseed/globalseq/*")
public class GlobalSeqController extends AbstractSafeseedController {


    private static final Log log =LogFactory.getLog(GlobalSeqController.class);

    @RequestMapping(value = "list.html", method = RequestMethod.GET)
    public ModelAndView list()
    {
        log.debug("in list method for GlobalSeq");
        ModelMap model = new ModelMap();
        model.addAttribute("globalSeqList",safeseedDaoService.getGlobalSeqService().list());
        return new ModelAndView("/safeseed/globalseq/list",model);
    }

    @RequestMapping(value = "add.html", method = RequestMethod.GET)
    public ModelAndView add()
    {
        log.debug("in add method for GlobalSeq");
        ModelMap model = new ModelMap();
        GlobalSeq globalSeq = new GlobalSeq();
        model.addAttribute("globalSeq",globalSeq);
        return new ModelAndView("/safeseed/globalseq/edit",model);
    }

    @RequestMapping(value = "edit.html", method = RequestMethod.GET)
    public ModelAndView edit(@RequestParam("globalSeqId") Integer globalSeqId)
    {
        log.debug("in edit method for GlobalSeq");
        ModelMap model = new ModelMap();
        GlobalSeq globalSeq = safeseedDaoService.getGlobalSeqService().findById(globalSeqId);
        model.addAttribute("globalSeq",globalSeq);
        return new ModelAndView("/safeseed/globalseq/edit",model);
    }

    @RequestMapping(value = "show.html", method = RequestMethod.GET)
    public ModelAndView show(@RequestParam("globalSeqId") Integer globalSeqId)
    {
        log.debug("in show method for GlobalSeq");
        ModelMap model = new ModelMap();
        GlobalSeq globalSeq = safeseedDaoService.getGlobalSeqService().findById(globalSeqId);
        model.addAttribute("globalSeq",globalSeq);
        return new ModelAndView("/safeseed/globalseq/show",model);
    }

    @RequestMapping(value = "save.html", method = RequestMethod.POST)
    public String save(@ModelAttribute("globalSeq") GlobalSeq globalSeq)
    {
        log.debug("in save method for GlobalSeq");
        safeseedDaoService.getGlobalSeqService().saveOrUpdate(globalSeq);
        return "redirect:/safeseed/globalseq/list.html";
    }

    @RequestMapping(value = "delete.html", method = RequestMethod.GET)
    public String delete(@RequestParam("globalSeqId") Integer globalSeqId)
    {
        log.debug("in delete method for GlobalSeq");
        GlobalSeq globalSeq = safeseedDaoService.getGlobalSeqService().findById(globalSeqId);
        safeseedDaoService.getGlobalSeqService().delete(globalSeq);
        return "redirect:/safeseed/globalseq/list.html";
    }
    
}
