package edu.uiowa.icts.safeseed.controller;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import edu.uiowa.icts.safeseed.dao.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

/* Generated by Protogen
 *
Fri Mar 04 07:04:26 CST 2011 *
*/

@Controller
@RequestMapping("/safeseed/groupseq/*")
public class GroupSeqController extends AbstractSafeseedController {


    private static final Log log =LogFactory.getLog(GroupSeqController.class);

    @RequestMapping(value = "list.html", method = RequestMethod.GET)
    public ModelAndView list()
    {
        log.debug("in list method for GroupSeq");
        ModelMap model = new ModelMap();
        model.addAttribute("groupSeqList",safeseedDaoService.getGroupSeqService().list());
        return new ModelAndView("/safeseed/groupseq/list",model);
    }

    @RequestMapping(value = "add.html", method = RequestMethod.GET)
    public ModelAndView add()
    {
        log.debug("in add method for GroupSeq");
        ModelMap model = new ModelMap();
        GroupSeq groupSeq = new GroupSeq();
        model.addAttribute("groupSeq",groupSeq);
        model.addAttribute("groupList",safeseedDaoService.getGroupService().list());
        model.addAttribute("seqList",safeseedDaoService.getSeqService().list());
        return new ModelAndView("/safeseed/groupseq/edit",model);
    }

    @RequestMapping(value = "edit.html", method = RequestMethod.GET)
    public ModelAndView edit(@RequestParam("groupId") int groupId, @RequestParam("seqId") int seqId)
    {
        log.debug("in edit method for GroupSeq");
        ModelMap model = new ModelMap();
        GroupSeqId groupSeqId = new GroupSeqId();
        groupSeqId.setGroupId(groupId);
        groupSeqId.setSeqId(seqId);
        model.addAttribute("groupList",safeseedDaoService.getGroupService().list());
        model.addAttribute("seqList",safeseedDaoService.getSeqService().list());
        GroupSeq groupSeq = safeseedDaoService.getGroupSeqService().findById(groupSeqId);
        model.addAttribute("groupSeq",groupSeq);
        return new ModelAndView("/safeseed/groupseq/edit",model);
    }

    @RequestMapping(value = "show.html", method = RequestMethod.GET)
    public ModelAndView show(@RequestParam("groupId") int groupId, @RequestParam("seqId") int seqId)
    {
        log.debug("in show method for GroupSeq");
        ModelMap model = new ModelMap();
        GroupSeqId groupSeqId = new GroupSeqId();
        groupSeqId.setGroupId(groupId);
        groupSeqId.setSeqId(seqId);
        GroupSeq groupSeq = safeseedDaoService.getGroupSeqService().findById(groupSeqId);
        model.addAttribute("groupSeq",groupSeq);
        return new ModelAndView("/safeseed/groupseq/show",model);
    }

    @RequestMapping(value = "save.html", method = RequestMethod.POST)
    public String save(@RequestParam("group.groupId") Integer groupId, @RequestParam("seq.seqId") Integer seqId, @ModelAttribute("groupSeq") GroupSeq groupSeq)
    {
        log.debug("in save method for GroupSeq");
        GroupSeqId groupSeqId = new GroupSeqId();
        groupSeqId.setGroupId(groupId);
        groupSeqId.setSeqId(seqId);
            groupSeq.setId( groupSeqId);
        safeseedDaoService.getGroupSeqService().saveOrUpdate(groupSeq);
        return "redirect:/safeseed/groupseq/list.html";
    }

    @RequestMapping(value = "delete.html", method = RequestMethod.GET)
    public String delete(@RequestParam("groupId") int groupId, @RequestParam("seqId") int seqId)
    {
        log.debug("in delete method for GroupSeq");
        GroupSeqId groupSeqId = new GroupSeqId();
        groupSeqId.setGroupId(groupId);
        groupSeqId.setSeqId(seqId);
        GroupSeq groupSeq = safeseedDaoService.getGroupSeqService().findById(groupSeqId);
        safeseedDaoService.getGroupSeqService().delete(groupSeq);
        return "redirect:/safeseed/groupseq/list.html";
    }
    
}
