package edu.uiowa.icts.safeseed.controller;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import edu.uiowa.icts.safeseed.dao.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

/* Generated by Protogen
 *
Fri Mar 04 07:04:26 CST 2011 *
*/

@Controller
@RequestMapping("/safeseed/groupglobalseq/*")
public class GroupGlobalSeqController extends AbstractSafeseedController {


    private static final Log log =LogFactory.getLog(GroupGlobalSeqController.class);

    @RequestMapping(value = "list.html", method = RequestMethod.GET)
    public ModelAndView list()
    {
        log.debug("in list method for GroupGlobalSeq");
        ModelMap model = new ModelMap();
        model.addAttribute("groupGlobalSeqList",safeseedDaoService.getGroupGlobalSeqService().list());
        return new ModelAndView("/safeseed/groupglobalseq/list",model);
    }

    @RequestMapping(value = "add.html", method = RequestMethod.GET)
    public ModelAndView add()
    {
        log.debug("in add method for GroupGlobalSeq");
        ModelMap model = new ModelMap();
        GroupGlobalSeq groupGlobalSeq = new GroupGlobalSeq();
        model.addAttribute("groupGlobalSeq",groupGlobalSeq);
        model.addAttribute("groupList",safeseedDaoService.getGroupService().list());
        model.addAttribute("globalSeqList",safeseedDaoService.getGlobalSeqService().list());
        return new ModelAndView("/safeseed/groupglobalseq/edit",model);
    }

    @RequestMapping(value = "edit.html", method = RequestMethod.GET)
    public ModelAndView edit(@RequestParam("groupId") int groupId, @RequestParam("globalSeqId") int globalSeqId)
    {
        log.debug("in edit method for GroupGlobalSeq");
        ModelMap model = new ModelMap();
        GroupGlobalSeqId groupGlobalSeqId = new GroupGlobalSeqId();
        groupGlobalSeqId.setGroupId(groupId);
        groupGlobalSeqId.setGlobalSeqId(globalSeqId);
        model.addAttribute("groupList",safeseedDaoService.getGroupService().list());
        model.addAttribute("globalSeqList",safeseedDaoService.getGlobalSeqService().list());
        GroupGlobalSeq groupGlobalSeq = safeseedDaoService.getGroupGlobalSeqService().findById(groupGlobalSeqId);
        model.addAttribute("groupGlobalSeq",groupGlobalSeq);
        return new ModelAndView("/safeseed/groupglobalseq/edit",model);
    }

    @RequestMapping(value = "show.html", method = RequestMethod.GET)
    public ModelAndView show(@RequestParam("groupId") int groupId, @RequestParam("globalSeqId") int globalSeqId)
    {
        log.debug("in show method for GroupGlobalSeq");
        ModelMap model = new ModelMap();
        GroupGlobalSeqId groupGlobalSeqId = new GroupGlobalSeqId();
        groupGlobalSeqId.setGroupId(groupId);
        groupGlobalSeqId.setGlobalSeqId(globalSeqId);
        GroupGlobalSeq groupGlobalSeq = safeseedDaoService.getGroupGlobalSeqService().findById(groupGlobalSeqId);
        model.addAttribute("groupGlobalSeq",groupGlobalSeq);
        return new ModelAndView("/safeseed/groupglobalseq/show",model);
    }

    @RequestMapping(value = "save.html", method = RequestMethod.POST)
    public String save(@RequestParam("group.groupId") Integer groupId, @RequestParam("globalSeq.globalSeqId") Integer globalSeqId, @ModelAttribute("groupGlobalSeq") GroupGlobalSeq groupGlobalSeq)
    {
        log.debug("in save method for GroupGlobalSeq");
        GroupGlobalSeqId groupGlobalSeqId = new GroupGlobalSeqId();
        groupGlobalSeqId.setGroupId(groupId);
        groupGlobalSeqId.setGlobalSeqId(globalSeqId);
            groupGlobalSeq.setId( groupGlobalSeqId);
        safeseedDaoService.getGroupGlobalSeqService().saveOrUpdate(groupGlobalSeq);
        return "redirect:/safeseed/groupglobalseq/list.html";
    }

    @RequestMapping(value = "delete.html", method = RequestMethod.GET)
    public String delete(@RequestParam("groupId") int groupId, @RequestParam("globalSeqId") int globalSeqId)
    {
        log.debug("in delete method for GroupGlobalSeq");
        GroupGlobalSeqId groupGlobalSeqId = new GroupGlobalSeqId();
        groupGlobalSeqId.setGroupId(groupId);
        groupGlobalSeqId.setGlobalSeqId(globalSeqId);
        GroupGlobalSeq groupGlobalSeq = safeseedDaoService.getGroupGlobalSeqService().findById(groupGlobalSeqId);
        safeseedDaoService.getGroupGlobalSeqService().delete(groupGlobalSeq);
        return "redirect:/safeseed/groupglobalseq/list.html";
    }
    
}
