package edu.uiowa.icts.safeseed.controller;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import edu.uiowa.icts.safeseed.dao.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

/* Generated by Protogen
 *
Fri Mar 04 07:04:26 CST 2011 *
*/

@Controller
@RequestMapping("/safeseed/history/*")
public class HistoryController extends AbstractSafeseedController {


    private static final Log log =LogFactory.getLog(HistoryController.class);

    @RequestMapping(value = "list.html", method = RequestMethod.GET)
    public ModelAndView list()
    {
        log.debug("in list method for History");
        ModelMap model = new ModelMap();
        model.addAttribute("historyList",safeseedDaoService.getHistoryService().list());
        return new ModelAndView("/safeseed/history/list",model);
    }

    @RequestMapping(value = "add.html", method = RequestMethod.GET)
    public ModelAndView add()
    {
        log.debug("in add method for History");
        ModelMap model = new ModelMap();
        History history = new History();
        model.addAttribute("history",history);
        model.addAttribute("seqFragList",safeseedDaoService.getSeqFragService().list());
        model.addAttribute("personList",safeseedDaoService.getPersonService().list());
        return new ModelAndView("/safeseed/history/edit",model);
    }

    @RequestMapping(value = "edit.html", method = RequestMethod.GET)
    public ModelAndView edit(@RequestParam("historyId") Integer historyId)
    {
        log.debug("in edit method for History");
        ModelMap model = new ModelMap();
        model.addAttribute("seqFragList",safeseedDaoService.getSeqFragService().list());
        model.addAttribute("personList",safeseedDaoService.getPersonService().list());
        History history = safeseedDaoService.getHistoryService().findById(historyId);
        model.addAttribute("history",history);
        return new ModelAndView("/safeseed/history/edit",model);
    }

    @RequestMapping(value = "show.html", method = RequestMethod.GET)
    public ModelAndView show(@RequestParam("historyId") Integer historyId)
    {
        log.debug("in show method for History");
        ModelMap model = new ModelMap();
        History history = safeseedDaoService.getHistoryService().findById(historyId);
        model.addAttribute("history",history);
        return new ModelAndView("/safeseed/history/show",model);
    }

    @RequestMapping(value = "save.html", method = RequestMethod.POST)
    public String save(@RequestParam("seqFrag.seqFragId") Integer seqFragId, @RequestParam("person.personId") Integer personId, @ModelAttribute("history") History history)
    {
        log.debug("in save method for History");
        history.setSeqFrag(safeseedDaoService.getSeqFragService().findById(seqFragId));
        history.setPerson(safeseedDaoService.getPersonService().findById(personId));
        safeseedDaoService.getHistoryService().saveOrUpdate(history);
        return "redirect:/safeseed/history/list.html";
    }

    @RequestMapping(value = "delete.html", method = RequestMethod.GET)
    public String delete(@RequestParam("historyId") Integer historyId)
    {
        log.debug("in delete method for History");
        History history = safeseedDaoService.getHistoryService().findById(historyId);
        safeseedDaoService.getHistoryService().delete(history);
        return "redirect:/safeseed/history/list.html";
    }
    
}
