package edu.uiowa.icts.safeseed.controller;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import edu.uiowa.icts.safeseed.dao.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

/* Generated by Protogen
 *
Fri Mar 04 07:04:26 CST 2011 *
*/

@Controller
@RequestMapping("/safeseed/persongroup/*")
public class PersonGroupController extends AbstractSafeseedController {


    private static final Log log =LogFactory.getLog(PersonGroupController.class);

    @RequestMapping(value = "list.html", method = RequestMethod.GET)
    public ModelAndView list()
    {
        log.debug("in list method for PersonGroup");
        ModelMap model = new ModelMap();
        model.addAttribute("personGroupList",safeseedDaoService.getPersonGroupService().list());
        return new ModelAndView("/safeseed/persongroup/list",model);
    }

    @RequestMapping(value = "add.html", method = RequestMethod.GET)
    public ModelAndView add()
    {
        log.debug("in add method for PersonGroup");
        ModelMap model = new ModelMap();
        PersonGroup personGroup = new PersonGroup();
        model.addAttribute("personGroup",personGroup);
        model.addAttribute("groupList",safeseedDaoService.getGroupService().list());
        model.addAttribute("personList",safeseedDaoService.getPersonService().list());
        return new ModelAndView("/safeseed/persongroup/edit",model);
    }

    @RequestMapping(value = "edit.html", method = RequestMethod.GET)
    public ModelAndView edit(@RequestParam("personId") int personId, @RequestParam("groupId") int groupId)
    {
        log.debug("in edit method for PersonGroup");
        ModelMap model = new ModelMap();
        PersonGroupId personGroupId = new PersonGroupId();
        personGroupId.setPersonId(personId);
        personGroupId.setGroupId(groupId);
        model.addAttribute("groupList",safeseedDaoService.getGroupService().list());
        model.addAttribute("personList",safeseedDaoService.getPersonService().list());
        PersonGroup personGroup = safeseedDaoService.getPersonGroupService().findById(personGroupId);
        model.addAttribute("personGroup",personGroup);
        return new ModelAndView("/safeseed/persongroup/edit",model);
    }

    @RequestMapping(value = "show.html", method = RequestMethod.GET)
    public ModelAndView show(@RequestParam("personId") int personId, @RequestParam("groupId") int groupId)
    {
        log.debug("in show method for PersonGroup");
        ModelMap model = new ModelMap();
        PersonGroupId personGroupId = new PersonGroupId();
        personGroupId.setPersonId(personId);
        personGroupId.setGroupId(groupId);
        PersonGroup personGroup = safeseedDaoService.getPersonGroupService().findById(personGroupId);
        model.addAttribute("personGroup",personGroup);
        return new ModelAndView("/safeseed/persongroup/show",model);
    }

    @RequestMapping(value = "save.html", method = RequestMethod.POST)
    public String save(@RequestParam("group.groupId") Integer groupId, @RequestParam("person.personId") Integer personId, @ModelAttribute("personGroup") PersonGroup personGroup)
    {
        log.debug("in save method for PersonGroup");
        PersonGroupId personGroupId = new PersonGroupId();
        personGroupId.setGroupId(groupId);
        personGroupId.setPersonId(personId);
            personGroup.setId( personGroupId);
        safeseedDaoService.getPersonGroupService().saveOrUpdate(personGroup);
        return "redirect:/safeseed/persongroup/list.html";
    }

    @RequestMapping(value = "delete.html", method = RequestMethod.GET)
    public String delete(@RequestParam("personId") int personId, @RequestParam("groupId") int groupId)
    {
        log.debug("in delete method for PersonGroup");
        PersonGroupId personGroupId = new PersonGroupId();
        personGroupId.setPersonId(personId);
        personGroupId.setGroupId(groupId);
        PersonGroup personGroup = safeseedDaoService.getPersonGroupService().findById(personGroupId);
        safeseedDaoService.getPersonGroupService().delete(personGroup);
        return "redirect:/safeseed/persongroup/list.html";
    }
    
}
