package edu.uiowa.icts.safeseed.controller;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import edu.uiowa.icts.safeseed.dao.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

/* Generated by Protogen
 *
Wed Apr 27 09:37:08 CDT 2011 *
*/

@Controller
@RequestMapping("/safeseed/searchresult/*")
public class SearchResultController extends AbstractSafeseedController {


    private static final Log log =LogFactory.getLog(SearchResultController.class);

    @RequestMapping(value = "list.html", method = RequestMethod.GET)
    public ModelAndView list()
    {
        log.debug("in list method for SearchResult");
        ModelMap model = new ModelMap();
        model.addAttribute("searchResultList",safeseedDaoService.getSearchResultService().list());
        return new ModelAndView("/safeseed/searchresult/list",model);
    }

    @RequestMapping(value = "add.html", method = RequestMethod.GET)
    public ModelAndView add()
    {
        log.debug("in add method for SearchResult");
        ModelMap model = new ModelMap();
        SearchResult searchResult = new SearchResult();
        model.addAttribute("searchResult",searchResult);
        model.addAttribute("searchStatusList",safeseedDaoService.getSearchStatusService().list());
        return new ModelAndView("/safeseed/searchresult/edit",model);
    }

    @RequestMapping(value = "edit.html", method = RequestMethod.GET)
    public ModelAndView edit(@RequestParam("searchResultId") Integer searchResultId)
    {
        log.debug("in edit method for SearchResult");
        ModelMap model = new ModelMap();
        model.addAttribute("searchStatusList",safeseedDaoService.getSearchStatusService().list());
        SearchResult searchResult = safeseedDaoService.getSearchResultService().findById(searchResultId);
        model.addAttribute("searchResult",searchResult);
        return new ModelAndView("/safeseed/searchresult/edit",model);
    }

    @RequestMapping(value = "show.html", method = RequestMethod.GET)
    public ModelAndView show(@RequestParam("searchResultId") Integer searchResultId)
    {
        log.debug("in show method for SearchResult");
        ModelMap model = new ModelMap();
        SearchResult searchResult = safeseedDaoService.getSearchResultService().findById(searchResultId);
        model.addAttribute("searchResult",searchResult);
        return new ModelAndView("/safeseed/searchresult/show",model);
    }

    @RequestMapping(value = "save.html", method = RequestMethod.POST)
    public String save(@RequestParam("searchStatus.searchSeq") String searchSeq, @ModelAttribute("searchResult") SearchResult searchResult)
    {
        log.debug("in save method for SearchResult");
        searchResult.setSearchStatus(safeseedDaoService.getSearchStatusService().findById(searchSeq));
        safeseedDaoService.getSearchResultService().saveOrUpdate(searchResult);
        return "redirect:/safeseed/searchresult/list.html";
    }

    @RequestMapping(value = "delete.html", method = RequestMethod.GET)
    public String delete(@RequestParam("searchResultId") Integer searchResultId)
    {
        log.debug("in delete method for SearchResult");
        SearchResult searchResult = safeseedDaoService.getSearchResultService().findById(searchResultId);
        safeseedDaoService.getSearchResultService().delete(searchResult);
        return "redirect:/safeseed/searchresult/list.html";
    }
}
