package edu.uiowa.icts.safeseed.controller;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import edu.uiowa.icts.safeseed.dao.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

/* Generated by Protogen
 *
Fri Mar 04 07:04:26 CST 2011 *
*/

@Controller
@RequestMapping("/safeseed/seqfrag/*")
public class SeqFragController extends AbstractSafeseedController {


    private static final Log log =LogFactory.getLog(SeqFragController.class);

    @RequestMapping(value = "list.html", method = RequestMethod.GET)
    public ModelAndView list()
    {
        log.debug("in list method for SeqFrag");
        ModelMap model = new ModelMap();
        model.addAttribute("seqFragList",safeseedDaoService.getSeqFragService().list());
        return new ModelAndView("/safeseed/seqfrag/list",model);
    }

    @RequestMapping(value = "add.html", method = RequestMethod.GET)
    public ModelAndView add()
    {
        log.debug("in add method for SeqFrag");
        ModelMap model = new ModelMap();
        SeqFrag seqFrag = new SeqFrag();
        model.addAttribute("seqFrag",seqFrag);
        model.addAttribute("seqList",safeseedDaoService.getSeqService().list());
        return new ModelAndView("/safeseed/seqfrag/edit",model);
    }

    @RequestMapping(value = "edit.html", method = RequestMethod.GET)
    public ModelAndView edit(@RequestParam("seqFragId") Integer seqFragId)
    {
        log.debug("in edit method for SeqFrag");
        ModelMap model = new ModelMap();
        model.addAttribute("seqList",safeseedDaoService.getSeqService().list());
        SeqFrag seqFrag = safeseedDaoService.getSeqFragService().findById(seqFragId);
        model.addAttribute("seqFrag",seqFrag);
        return new ModelAndView("/safeseed/seqfrag/edit",model);
    }

    @RequestMapping(value = "show.html", method = RequestMethod.GET)
    public ModelAndView show(@RequestParam("seqFragId") Integer seqFragId)
    {
        log.debug("in show method for SeqFrag");
        ModelMap model = new ModelMap();
        SeqFrag seqFrag = safeseedDaoService.getSeqFragService().findById(seqFragId);
        model.addAttribute("seqFrag",seqFrag);
        return new ModelAndView("/safeseed/seqfrag/show",model);
    }

    @RequestMapping(value = "save.html", method = RequestMethod.POST)
    public String save(@RequestParam("seq.seqId") Integer seqId, @ModelAttribute("seqFrag") SeqFrag seqFrag)
    {
        log.debug("in save method for SeqFrag");
        seqFrag.setSeq(safeseedDaoService.getSeqService().findById(seqId));
        safeseedDaoService.getSeqFragService().saveOrUpdate(seqFrag);
        return "redirect:/safeseed/seqfrag/list.html";
    }

    @RequestMapping(value = "delete.html", method = RequestMethod.GET)
    public String delete(@RequestParam("seqFragId") Integer seqFragId)
    {
        log.debug("in delete method for SeqFrag");
        SeqFrag seqFrag = safeseedDaoService.getSeqFragService().findById(seqFragId);
        safeseedDaoService.getSeqFragService().delete(seqFrag);
        return "redirect:/safeseed/seqfrag/list.html";
    }
    
}
