package edu.uiowa.icts.safeseed.controller;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import edu.uiowa.icts.safeseed.dao.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

/* Generated by Protogen
 *
Fri Mar 04 07:04:26 CST 2011 *
*/

@Controller
@RequestMapping("/safeseed/submission/*")
public class SubmissionController extends AbstractSafeseedController {


    private static final Log log =LogFactory.getLog(SubmissionController.class);

    @RequestMapping(value = "list.html", method = RequestMethod.GET)
    public ModelAndView list()
    {
        log.debug("in list method for Submission");
        ModelMap model = new ModelMap();
        model.addAttribute("submissionList",safeseedDaoService.getSubmissionService().list());
        return new ModelAndView("/safeseed/submission/list",model);
    }

    @RequestMapping(value = "add.html", method = RequestMethod.GET)
    public ModelAndView add()
    {
        log.debug("in add method for Submission");
        ModelMap model = new ModelMap();
        Submission submission = new Submission();
        model.addAttribute("submission",submission);
        model.addAttribute("seqFragList",safeseedDaoService.getSeqFragService().list());
        model.addAttribute("personList",safeseedDaoService.getPersonService().list());
        model.addAttribute("seqList",safeseedDaoService.getSeqService().list());
        return new ModelAndView("/safeseed/submission/edit",model);
    }

    @RequestMapping(value = "edit.html", method = RequestMethod.GET)
    public ModelAndView edit(@RequestParam("submissionId") Integer submissionId)
    {
        log.debug("in edit method for Submission");
        ModelMap model = new ModelMap();
        model.addAttribute("seqFragList",safeseedDaoService.getSeqFragService().list());
        model.addAttribute("personList",safeseedDaoService.getPersonService().list());
        model.addAttribute("seqList",safeseedDaoService.getSeqService().list());
        Submission submission = safeseedDaoService.getSubmissionService().findById(submissionId);
        model.addAttribute("submission",submission);
        return new ModelAndView("/safeseed/submission/edit",model);
    }

    @RequestMapping(value = "show.html", method = RequestMethod.GET)
    public ModelAndView show(@RequestParam("submissionId") Integer submissionId)
    {
        log.debug("in show method for Submission");
        ModelMap model = new ModelMap();
        Submission submission = safeseedDaoService.getSubmissionService().findById(submissionId);
        model.addAttribute("submission",submission);
        return new ModelAndView("/safeseed/submission/show",model);
    }

    @RequestMapping(value = "save.html", method = RequestMethod.POST)
    public String save(@RequestParam("seqFrag.seqFragId") Integer seqFragId, @RequestParam("person.personId") Integer personId, @RequestParam("seq.seqId") Integer seqId, @ModelAttribute("submission") Submission submission)
    {
        log.debug("in save method for Submission");
        submission.setSeqFrag(safeseedDaoService.getSeqFragService().findById(seqFragId));
        submission.setPerson(safeseedDaoService.getPersonService().findById(personId));
        submission.setSeq(safeseedDaoService.getSeqService().findById(seqId));
        safeseedDaoService.getSubmissionService().saveOrUpdate(submission);
        return "redirect:/safeseed/submission/list.html";
    }

    @RequestMapping(value = "delete.html", method = RequestMethod.GET)
    public String delete(@RequestParam("submissionId") Integer submissionId)
    {
        log.debug("in delete method for Submission");
        Submission submission = safeseedDaoService.getSubmissionService().findById(submissionId);
        safeseedDaoService.getSubmissionService().delete(submission);
        return "redirect:/safeseed/submission/list.html";
    }
    
}
