package edu.uiowa.icts.safeseed.controller;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import edu.uiowa.icts.safeseed.dao.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

/* Generated by Protogen
 *
Fri Mar 04 07:04:26 CST 2011 *
*/

@Controller
@RequestMapping("/safeseed/systemsetting/*")
public class SystemSettingController extends AbstractSafeseedController {


    private static final Log log =LogFactory.getLog(SystemSettingController.class);

    @RequestMapping(value = "list.html", method = RequestMethod.GET)
    public ModelAndView list()
    {
        log.debug("in list method for SystemSetting");
        ModelMap model = new ModelMap();
        model.addAttribute("systemSettingList",safeseedDaoService.getSystemSettingService().list());
        return new ModelAndView("/safeseed/systemsetting/list",model);
    }

    @RequestMapping(value = "add.html", method = RequestMethod.GET)
    public ModelAndView add()
    {
        log.debug("in add method for SystemSetting");
        ModelMap model = new ModelMap();
        SystemSetting systemSetting = new SystemSetting();
        model.addAttribute("systemSetting",systemSetting);
        return new ModelAndView("/safeseed/systemsetting/edit",model);
    }

    @RequestMapping(value = "edit.html", method = RequestMethod.GET)
    public ModelAndView edit(@RequestParam("systemSetting") String systemSettingId)
    {
        log.debug("in edit method for SystemSetting");
        ModelMap model = new ModelMap();
        SystemSetting systemSetting = safeseedDaoService.getSystemSettingService().findById(systemSettingId);
        model.addAttribute("systemSetting",systemSetting);
        return new ModelAndView("/safeseed/systemsetting/edit",model);
    }

    @RequestMapping(value = "show.html", method = RequestMethod.GET)
    public ModelAndView show(@RequestParam("systemSetting") String systemSettingId)
    {
        log.debug("in show method for SystemSetting");
        ModelMap model = new ModelMap();
        SystemSetting systemSetting = safeseedDaoService.getSystemSettingService().findById(systemSettingId);
        model.addAttribute("systemSetting",systemSetting);
        return new ModelAndView("/safeseed/systemsetting/show",model);
    }

    @RequestMapping(value = "save.html", method = RequestMethod.POST)
    public String save(@ModelAttribute("systemSetting") SystemSetting systemSetting)
    {
        log.debug("in save method for SystemSetting");
        safeseedDaoService.getSystemSettingService().saveOrUpdate(systemSetting);
        return "redirect:/safeseed/systemsetting/list.html";
    }

    @RequestMapping(value = "delete.html", method = RequestMethod.GET)
    public String delete(@RequestParam("systemSetting") String systemSettingId)
    {
        log.debug("in delete method for SystemSetting");
        SystemSetting systemSetting = safeseedDaoService.getSystemSettingService().findById(systemSettingId);
        safeseedDaoService.getSystemSettingService().delete(systemSetting);
        return "redirect:/safeseed/systemsetting/list.html";
    }
}