package edu.uiowa.icts.safeseed.domain;

import java.util.Set;
import java.util.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.springframework.format.annotation.DateTimeFormat;
import org.hibernate.annotations.*;
import javax.persistence.CascadeType;
import edu.uiowa.icts.*;

/* Generated by Protogen - www.icts.uiowa.edu/protogen
 * @date 2011/03/03 16:15:53
*/ 

@Entity(name="edu_uiowa_icts_safeseed_domain_collection")
@Table(name = "collection", schema="safeseed")
public class Collection
{
        private CollectionId collectionId;
        private String name;
        private String notes;
        @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date dateAdded;
        private Person person;
        private Seq seq;

    public Collection()    {
        this.collectionId = null;
        this.name = "";
        this.notes = "";
        this.dateAdded = null;
        this.person = null;
        this.seq = null;
    }

    public Collection(CollectionId collectionId, String name, String notes, Date dateAdded, Person person, Seq seq)
    {
        this.collectionId = collectionId;
        this.name = name;
        this.notes = notes;
        this.dateAdded = dateAdded;
        this.person = person;
        this.seq = seq;
    }

    /*****collectionId*****/
    @EmbeddedId
    @AttributeOverrides( {

    @AttributeOverride(name = "personId", column = @Column(name = "person_id", nullable = false))
    ,
    @AttributeOverride(name = "seqId", column = @Column(name = "seq_id", nullable = false))
    })
    public CollectionId getId()
    {
        return collectionId;
    }

    public void setId(CollectionId collectionId)
    {
        this.collectionId = collectionId;
    }

    /*****name*****/
    @Column(name = "name")
    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    /*****notes*****/
    @Column(name = "notes")
    public String getNotes()
    {
        return notes;
    }

    public void setNotes(String notes)
    {
        this.notes = notes;
    }

    /*****dateAdded*****/
    @Column(name = "date_added")
    public Date getDateAdded()
    {
        return dateAdded;
    }

    public void setDateAdded(Date dateAdded)
    {
        this.dateAdded = dateAdded;
    }

    public void setDateAdded(String dateAdded)
    {
        try{
        DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
        formatter.setLenient(true);        this.dateAdded = formatter.parse(dateAdded);
        } catch (ParseException e) {e.printStackTrace();}
    }

    /*****person*****/
    @ManyToOne(fetch = FetchType.LAZY,  targetEntity=Person.class )
    @JoinColumn(name = "person_id",nullable = false, insertable = false, updatable = false)
    public Person getPerson()
    {
        return person;
    }

    public void setPerson(Person person)
    {
        this.person = person;
    }

    /*****seq*****/
    @ManyToOne(fetch = FetchType.LAZY,  targetEntity=Seq.class )
    @JoinColumn(name = "seq_id",nullable = false, insertable = false, updatable = false)
    public Seq getSeq()
    {
        return seq;
    }

    public void setSeq(Seq seq)
    {
        this.seq = seq;
    }


}
