package edu.uiowa.icts.safeseed.domain;

import java.util.Set;
import java.util.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.springframework.format.annotation.DateTimeFormat;
import org.hibernate.annotations.*;
import javax.persistence.CascadeType;
import edu.uiowa.icts.*;

/* Generated by Protogen - www.icts.uiowa.edu/protogen
 * @date 2011/03/03 16:15:53
*/ 

@Entity(name="edu_uiowa_icts_safeseed_domain_frag")
@Table(name = "frag", schema="safeseed")
public class Frag
{
        private Integer fragId;
        private String startSeq;
        private Integer gcContentPercentage;
        private String three;
        private String four;
        private String nineteen;
        private String twenty;
        private Integer threePlusFour;
        private String potsNt;
        private SeqFrag seqFrag;

    public Frag()    {
        this.fragId = null;
        this.startSeq = "";
        this.gcContentPercentage = null;
        this.three = "";
        this.four = "";
        this.nineteen = "";
        this.twenty = "";
        this.threePlusFour = null;
        this.potsNt = "";
        this.seqFrag = null;
    }

    public Frag(Integer fragId, String startSeq, Integer gcContentPercentage, String three, String four, String nineteen, String twenty, Integer threePlusFour, String potsNt, SeqFrag seqFrag)
    {
        this.fragId = fragId;
        this.startSeq = startSeq;
        this.gcContentPercentage = gcContentPercentage;
        this.three = three;
        this.four = four;
        this.nineteen = nineteen;
        this.twenty = twenty;
        this.threePlusFour = threePlusFour;
        this.potsNt = potsNt;
        this.seqFrag = seqFrag;
    }

    /*****fragId*****/
    @javax.persistence.SequenceGenerator(  name="gen",  sequenceName="safeseed.seqnum",allocationSize=1)
    @Id
    @GeneratedValue( strategy=GenerationType.AUTO,generator="gen")
    @Column(name = "frag_id", unique = true, nullable = false)
    public Integer getFragId()
    {
        return fragId;
    }

    public void setFragId(Integer fragId)
    {
        this.fragId = fragId;
    }

    /*****startSeq*****/
    @Column(name = "start_seq")
    public String getStartSeq()
    {
        return startSeq;
    }

    public void setStartSeq(String startSeq)
    {
        this.startSeq = startSeq;
    }

    /*****gcContentPercentage*****/
    @Column(name = "gc_content_percentage")
    public Integer getGcContentPercentage()
    {
        return gcContentPercentage;
    }

    public void setGcContentPercentage(Integer gcContentPercentage)
    {
        this.gcContentPercentage = gcContentPercentage;
    }

    /*****three*****/
    @Column(name = "three")
    public String getThree()
    {
        return three;
    }

    public void setThree(String three)
    {
        this.three = three;
    }

    /*****four*****/
    @Column(name = "four")
    public String getFour()
    {
        return four;
    }

    public void setFour(String four)
    {
        this.four = four;
    }

    /*****nineteen*****/
    @Column(name = "nineteen")
    public String getNineteen()
    {
        return nineteen;
    }

    public void setNineteen(String nineteen)
    {
        this.nineteen = nineteen;
    }

    /*****twenty*****/
    @Column(name = "twenty")
    public String getTwenty()
    {
        return twenty;
    }

    public void setTwenty(String twenty)
    {
        this.twenty = twenty;
    }

    /*****threePlusFour*****/
    @Column(name = "three_plus_four")
    public Integer getThreePlusFour()
    {
        return threePlusFour;
    }

    public void setThreePlusFour(Integer threePlusFour)
    {
        this.threePlusFour = threePlusFour;
    }

    /*****potsNt*****/
    @Column(name = "pots_nt")
    public String getPotsNt()
    {
        return potsNt;
    }

    public void setPotsNt(String potsNt)
    {
        this.potsNt = potsNt;
    }

    /*****seqFrag*****/
    @ManyToOne(fetch = FetchType.LAZY,  targetEntity=SeqFrag.class )
    @JoinColumn(name = "seq_frag_id",nullable = true)
    public SeqFrag getSeqFrag()
    {
        return seqFrag;
    }

    public void setSeqFrag(SeqFrag seqFrag)
    {
        this.seqFrag = seqFrag;
    }


}
