package edu.uiowa.icts.safeseed.domain;

import java.util.Set;
import java.util.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.springframework.format.annotation.DateTimeFormat;
import org.hibernate.annotations.*;
import javax.persistence.CascadeType;
import edu.uiowa.icts.*;

/* Generated by Protogen - www.icts.uiowa.edu/protogen
 * @date 2011/03/03 16:15:53
*/ 

@Entity(name="edu_uiowa_icts_safeseed_domain_globalFrag")
@Table(name = "global_frag", schema="safeseed")
public class GlobalFrag
{
        private Integer globalFragId;
        private String startSeq;
        private Integer gcContentPercentage;
        private String three;
        private String four;
        private String nineteen;
        private String twenty;
        private Integer threePlusFour;
        private String potsNt;
        private GlobalSeqFrag globalSeqFrag;

    public GlobalFrag()    {
        this.globalFragId = null;
        this.startSeq = "";
        this.gcContentPercentage = null;
        this.three = "";
        this.four = "";
        this.nineteen = "";
        this.twenty = "";
        this.threePlusFour = null;
        this.potsNt = "";
        this.globalSeqFrag = null;
    }

    public GlobalFrag(Integer globalFragId, String startSeq, Integer gcContentPercentage, String three, String four, String nineteen, String twenty, Integer threePlusFour, String potsNt, GlobalSeqFrag globalSeqFrag)
    {
        this.globalFragId = globalFragId;
        this.startSeq = startSeq;
        this.gcContentPercentage = gcContentPercentage;
        this.three = three;
        this.four = four;
        this.nineteen = nineteen;
        this.twenty = twenty;
        this.threePlusFour = threePlusFour;
        this.potsNt = potsNt;
        this.globalSeqFrag = globalSeqFrag;
    }

    /*****globalFragId*****/
    @javax.persistence.SequenceGenerator(  name="gen",  sequenceName="safeseed.seqnum",allocationSize=1)
    @Id
    @GeneratedValue( strategy=GenerationType.AUTO,generator="gen")
    @Column(name = "global_frag_id", unique = true, nullable = false)
    public Integer getGlobalFragId()
    {
        return globalFragId;
    }

    public void setGlobalFragId(Integer globalFragId)
    {
        this.globalFragId = globalFragId;
    }

    /*****startSeq*****/
    @Column(name = "start_seq")
    public String getStartSeq()
    {
        return startSeq;
    }

    public void setStartSeq(String startSeq)
    {
        this.startSeq = startSeq;
    }

    /*****gcContentPercentage*****/
    @Column(name = "gc_content_percentage")
    public Integer getGcContentPercentage()
    {
        return gcContentPercentage;
    }

    public void setGcContentPercentage(Integer gcContentPercentage)
    {
        this.gcContentPercentage = gcContentPercentage;
    }

    /*****three*****/
    @Column(name = "three")
    public String getThree()
    {
        return three;
    }

    public void setThree(String three)
    {
        this.three = three;
    }

    /*****four*****/
    @Column(name = "four")
    public String getFour()
    {
        return four;
    }

    public void setFour(String four)
    {
        this.four = four;
    }

    /*****nineteen*****/
    @Column(name = "nineteen")
    public String getNineteen()
    {
        return nineteen;
    }

    public void setNineteen(String nineteen)
    {
        this.nineteen = nineteen;
    }

    /*****twenty*****/
    @Column(name = "twenty")
    public String getTwenty()
    {
        return twenty;
    }

    public void setTwenty(String twenty)
    {
        this.twenty = twenty;
    }

    /*****threePlusFour*****/
    @Column(name = "three_plus_four")
    public Integer getThreePlusFour()
    {
        return threePlusFour;
    }

    public void setThreePlusFour(Integer threePlusFour)
    {
        this.threePlusFour = threePlusFour;
    }

    /*****potsNt*****/
    @Column(name = "pots_nt")
    public String getPotsNt()
    {
        return potsNt;
    }

    public void setPotsNt(String potsNt)
    {
        this.potsNt = potsNt;
    }

    /*****globalSeqFrag*****/
    @ManyToOne(fetch = FetchType.LAZY,  targetEntity=GlobalSeqFrag.class )
    @JoinColumn(name = "global_seq_frag",nullable = true)
    public GlobalSeqFrag getGlobalSeqFrag()
    {
        return globalSeqFrag;
    }

    public void setGlobalSeqFrag(GlobalSeqFrag globalSeqFrag)
    {
        this.globalSeqFrag = globalSeqFrag;
    }


}
