package edu.uiowa.icts.safeseed.domain;

import java.util.Set;
import java.util.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.springframework.format.annotation.DateTimeFormat;
import org.hibernate.annotations.*;
import javax.persistence.CascadeType;
import edu.uiowa.icts.*;

/* Generated by Protogen - www.icts.uiowa.edu/protogen
 * @date 2011/03/03 16:15:53
*/ 

@Entity(name="edu_uiowa_icts_safeseed_domain_group")
@Table(name = "group", schema="safeseed")
public class Group
{
        private Integer groupId;
        private String name;
        private String description;
        private Set<GroupSeq> groupSeqs = new HashSet<GroupSeq>(0);
        private Set<PersonGroup> personGroups = new HashSet<PersonGroup>(0);
        private Set<GroupGlobalSeq> groupGlobalSeqs = new HashSet<GroupGlobalSeq>(0);

    public Group()    {
        this.groupId = null;
        this.name = "";
        this.description = "";
        this.groupSeqs = new HashSet<GroupSeq>(0);
        this.personGroups = new HashSet<PersonGroup>(0);
        this.groupGlobalSeqs = new HashSet<GroupGlobalSeq>(0);
    }

    public Group(Integer groupId, String name, String description, Set<GroupSeq> groupSeqs, Set<PersonGroup> personGroups, Set<GroupGlobalSeq> groupGlobalSeqs)
    {
        this.groupId = groupId;
        this.name = name;
        this.description = description;
        this.groupSeqs = groupSeqs;
        this.personGroups = personGroups;
        this.groupGlobalSeqs = groupGlobalSeqs;
    }

    /*****groupId*****/
    @javax.persistence.SequenceGenerator(  name="gen",  sequenceName="safeseed.seqnum",allocationSize=1)
    @Id
    @GeneratedValue( strategy=GenerationType.AUTO,generator="gen")
    @Column(name = "group_id", unique = true, nullable = false)
    public Integer getGroupId()
    {
        return groupId;
    }

    public void setGroupId(Integer groupId)
    {
        this.groupId = groupId;
    }

    /*****name*****/
    @Column(name = "name")
    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    /*****description*****/
    @Column(name = "description")
    public String getDescription()
    {
        return description;
    }

    public void setDescription(String description)
    {
        this.description = description;
    }

    /*****groupSeqs*****/
    @OneToMany(fetch = FetchType.LAZY,   mappedBy = "group", targetEntity=GroupSeq.class, cascade=CascadeType.REMOVE)
    public Set<GroupSeq> getGroupSeqs()
    {
        return groupSeqs;
    }

    public void setGroupSeqs(Set<GroupSeq> groupSeqs)
    {
        this.groupSeqs = groupSeqs;
    }

    /*****personGroups*****/
    @OneToMany(fetch = FetchType.LAZY,   mappedBy = "group", targetEntity=PersonGroup.class, cascade=CascadeType.REMOVE)
    public Set<PersonGroup> getPersonGroups()
    {
        return personGroups;
    }

    public void setPersonGroups(Set<PersonGroup> personGroups)
    {
        this.personGroups = personGroups;
    }

    /*****groupGlobalSeqs*****/
    @OneToMany(fetch = FetchType.LAZY,   mappedBy = "group", targetEntity=GroupGlobalSeq.class, cascade=CascadeType.REMOVE)
    public Set<GroupGlobalSeq> getGroupGlobalSeqs()
    {
        return groupGlobalSeqs;
    }

    public void setGroupGlobalSeqs(Set<GroupGlobalSeq> groupGlobalSeqs)
    {
        this.groupGlobalSeqs = groupGlobalSeqs;
    }


}
