package edu.uiowa.icts.safeseed.domain;

import java.util.Set;
import java.util.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.springframework.format.annotation.DateTimeFormat;
import org.hibernate.annotations.*;
import javax.persistence.CascadeType;
import edu.uiowa.icts.*;

/* Generated by Protogen - www.icts.uiowa.edu/protogen
 * @date 2011/03/03 16:15:53
*/ 

@Entity(name="edu_uiowa_icts_safeseed_domain_groupSeq")
@Table(name = "group_seq", schema="safeseed")
public class GroupSeq
{
        private GroupSeqId groupSeqId;
        private String name;
        private String notes;
        @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date dateAdded;
        private Group group;
        private Seq seq;

    public GroupSeq()    {
        this.groupSeqId = null;
        this.name = "";
        this.notes = "";
        this.dateAdded = null;
        this.group = null;
        this.seq = null;
    }

    public GroupSeq(GroupSeqId groupSeqId, String name, String notes, Date dateAdded, Group group, Seq seq)
    {
        this.groupSeqId = groupSeqId;
        this.name = name;
        this.notes = notes;
        this.dateAdded = dateAdded;
        this.group = group;
        this.seq = seq;
    }

    /*****groupSeqId*****/
    @EmbeddedId
    @AttributeOverrides( {

    @AttributeOverride(name = "groupId", column = @Column(name = "group_id", nullable = false))
    ,
    @AttributeOverride(name = "seqId", column = @Column(name = "seq_id", nullable = false))
    })
    public GroupSeqId getId()
    {
        return groupSeqId;
    }

    public void setId(GroupSeqId groupSeqId)
    {
        this.groupSeqId = groupSeqId;
    }

    /*****name*****/
    @Column(name = "name")
    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    /*****notes*****/
    @Column(name = "notes")
    public String getNotes()
    {
        return notes;
    }

    public void setNotes(String notes)
    {
        this.notes = notes;
    }

    /*****dateAdded*****/
    @Column(name = "date_added")
    public Date getDateAdded()
    {
        return dateAdded;
    }

    public void setDateAdded(Date dateAdded)
    {
        this.dateAdded = dateAdded;
    }

    public void setDateAdded(String dateAdded)
    {
        try{
        DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
        formatter.setLenient(true);        this.dateAdded = formatter.parse(dateAdded);
        } catch (ParseException e) {e.printStackTrace();}
    }

    /*****group*****/
    @ManyToOne(fetch = FetchType.LAZY,  targetEntity=Group.class )
    @JoinColumn(name = "group_id",nullable = false, insertable = false, updatable = false)
    public Group getGroup()
    {
        return group;
    }

    public void setGroup(Group group)
    {
        this.group = group;
    }

    /*****seq*****/
    @ManyToOne(fetch = FetchType.LAZY,  targetEntity=Seq.class )
    @JoinColumn(name = "seq_id",nullable = false, insertable = false, updatable = false)
    public Seq getSeq()
    {
        return seq;
    }

    public void setSeq(Seq seq)
    {
        this.seq = seq;
    }


}
