package edu.uiowa.icts.safeseed.domain;

import java.util.Set;
import java.util.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.springframework.format.annotation.DateTimeFormat;
import org.hibernate.annotations.*;
import javax.persistence.CascadeType;
import edu.uiowa.icts.*;

/* Generated by Protogen - www.icts.uiowa.edu/protogen
 * @date 2011/03/03 16:15:53
*/ 

@Entity(name="edu_uiowa_icts_safeseed_domain_groupGlobalSeq")
@Table(name = "group_global_seq", schema="safeseed")
public class GroupGlobalSeq
{
        private GroupGlobalSeqId groupGlobalSeqId;
        private String label;
        private String notes;
        @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date dateAdded;
        private Group group;
        private GlobalSeq globalSeq;

    public GroupGlobalSeq()    {
        this.groupGlobalSeqId = null;
        this.label = "";
        this.notes = "";
        this.dateAdded = null;
        this.group = null;
        this.globalSeq = null;
    }

    public GroupGlobalSeq(GroupGlobalSeqId groupGlobalSeqId, String label, String notes, Date dateAdded, Group group, GlobalSeq globalSeq)
    {
        this.groupGlobalSeqId = groupGlobalSeqId;
        this.label = label;
        this.notes = notes;
        this.dateAdded = dateAdded;
        this.group = group;
        this.globalSeq = globalSeq;
    }

    /*****groupGlobalSeqId*****/
    @EmbeddedId
    @AttributeOverrides( {

    @AttributeOverride(name = "groupId", column = @Column(name = "group_id", nullable = false))
    ,
    @AttributeOverride(name = "globalSeqId", column = @Column(name = "global_seq_id", nullable = false))
    })
    public GroupGlobalSeqId getId()
    {
        return groupGlobalSeqId;
    }

    public void setId(GroupGlobalSeqId groupGlobalSeqId)
    {
        this.groupGlobalSeqId = groupGlobalSeqId;
    }

    /*****label*****/
    @Column(name = "label")
    public String getLabel()
    {
        return label;
    }

    public void setLabel(String label)
    {
        this.label = label;
    }

    /*****notes*****/
    @Column(name = "notes")
    public String getNotes()
    {
        return notes;
    }

    public void setNotes(String notes)
    {
        this.notes = notes;
    }

    /*****dateAdded*****/
    @Column(name = "date_added")
    public Date getDateAdded()
    {
        return dateAdded;
    }

    public void setDateAdded(Date dateAdded)
    {
        this.dateAdded = dateAdded;
    }

    public void setDateAdded(String dateAdded)
    {
        try{
        DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
        formatter.setLenient(true);        this.dateAdded = formatter.parse(dateAdded);
        } catch (ParseException e) {e.printStackTrace();}
    }

    /*****group*****/
    @ManyToOne(fetch = FetchType.LAZY,  targetEntity=Group.class )
    @JoinColumn(name = "group_id",nullable = false, insertable = false, updatable = false)
    public Group getGroup()
    {
        return group;
    }

    public void setGroup(Group group)
    {
        this.group = group;
    }

    /*****globalSeq*****/
    @ManyToOne(fetch = FetchType.LAZY,  targetEntity=GlobalSeq.class )
    @JoinColumn(name = "global_seq_id",nullable = false, insertable = false, updatable = false)
    public GlobalSeq getGlobalSeq()
    {
        return globalSeq;
    }

    public void setGlobalSeq(GlobalSeq globalSeq)
    {
        this.globalSeq = globalSeq;
    }


}
