package edu.uiowa.icts.safeseed.domain;

/* Generated by Protogen - www.icts.uiowa.edu/protogen
 * @date 2011/03/03 16:15:53
*/ 

import java.util.Set;
import java.util.*;
import edu.uiowa.icts.*;
import javax.persistence.*;
import java.io.Serializable;
import org.springframework.format.annotation.DateTimeFormat;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;


@Embeddable
public class GroupGlobalSeqId implements Serializable
{


    //Table attribute definitions
    private Integer groupId;
    private Integer globalSeqId;




    //Table attribute definitions
    @Column(name = "group_id", nullable = false)
    public Integer getGroupId()
    {
        return groupId;
    }

    public void setGroupId(Integer groupId)
    {
        this.groupId = groupId;
    }

    @Column(name = "global_seq_id", nullable = false)
    public Integer getGlobalSeqId()
    {
        return globalSeqId;
    }

    public void setGlobalSeqId(Integer globalSeqId)
    {
        this.globalSeqId = globalSeqId;
    }

}