package edu.uiowa.icts.safeseed.domain;

import java.util.Set;
import java.util.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.springframework.format.annotation.DateTimeFormat;
import org.hibernate.annotations.*;
import javax.persistence.CascadeType;
import edu.uiowa.icts.*;

/* Generated by Protogen - www.icts.uiowa.edu/protogen
 * @date 2011/03/03 16:15:53
*/ 

@Entity(name="edu_uiowa_icts_safeseed_domain_personGroup")
@Table(name = "person_group", schema="safeseed")
public class PersonGroup
{
        private PersonGroupId personGroupId;
        private String role;
        private Group group;
        private Person person;

    public PersonGroup()    {
        this.personGroupId = null;
        this.role = "";
        this.group = null;
        this.person = null;
    }

    public PersonGroup(PersonGroupId personGroupId, String role, Group group, Person person)
    {
        this.personGroupId = personGroupId;
        this.role = role;
        this.group = group;
        this.person = person;
    }

    /*****personGroupId*****/
    @EmbeddedId
    @AttributeOverrides( {

    @AttributeOverride(name = "personId", column = @Column(name = "person_id", nullable = false))
    ,
    @AttributeOverride(name = "groupId", column = @Column(name = "group_id", nullable = false))
    })
    public PersonGroupId getId()
    {
        return personGroupId;
    }

    public void setId(PersonGroupId personGroupId)
    {
        this.personGroupId = personGroupId;
    }

    /*****role*****/
    @Column(name = "role")
    public String getRole()
    {
        return role;
    }

    public void setRole(String role)
    {
        this.role = role;
    }

    /*****group*****/
    @ManyToOne(fetch = FetchType.LAZY,  targetEntity=Group.class )
    @JoinColumn(name = "group_id",nullable = false, insertable = false, updatable = false)
    public Group getGroup()
    {
        return group;
    }

    public void setGroup(Group group)
    {
        this.group = group;
    }

    /*****person*****/
    @ManyToOne(fetch = FetchType.LAZY,  targetEntity=Person.class )
    @JoinColumn(name = "person_id",nullable = false, insertable = false, updatable = false)
    public Person getPerson()
    {
        return person;
    }

    public void setPerson(Person person)
    {
        this.person = person;
    }


}
