package edu.uiowa.icts.safeseed.domain;

import java.util.Set;
import java.util.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.springframework.format.annotation.DateTimeFormat;
import org.hibernate.annotations.*;
import javax.persistence.CascadeType;
import edu.uiowa.icts.*;

/* Generated by Protogen - www.icts.uiowa.edu/protogen
 * @date 2011/04/26 15:23:46
*/ 

@Entity(name="edu_uiowa_icts_safeseed_domain_searchResult")
@Table(name = "search_result", schema="safeseed")
public class SearchResult
{
        private Integer searchResultId;
        private String searchSeqRc;
        private String resultSeq;
        private String resultAccession;
        private Integer resultAccessionOffset;
        private Integer resultOffset;
        @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date timeStamp;
        private SearchStatus searchStatus;

    public SearchResult()    {
        this.searchResultId = null;
        this.searchSeqRc = "";
        this.resultSeq = "";
        this.resultAccession = "";
        this.resultAccessionOffset = null;
        this.resultOffset = null;
        this.timeStamp = null;
        this.searchStatus = null;
    }

    public SearchResult(Integer searchResultId, String searchSeqRc, String resultSeq, String resultAccession, Integer resultAccessionOffset, Integer resultOffset, Date timeStamp, SearchStatus searchStatus)
    {
        this.searchResultId = searchResultId;
        this.searchSeqRc = searchSeqRc;
        this.resultSeq = resultSeq;
        this.resultAccession = resultAccession;
        this.resultAccessionOffset = resultAccessionOffset;
        this.resultOffset = resultOffset;
        this.timeStamp = timeStamp;
        this.searchStatus = searchStatus;
    }

    /*****searchResultId*****/
    @javax.persistence.SequenceGenerator(  name="gen",  sequenceName="safeseed.seqnum",allocationSize=1)
    @Id
    @GeneratedValue( strategy=GenerationType.AUTO,generator="gen")
    @Column(name = "search_result_id", unique = true, nullable = false)
    public Integer getSearchResultId()
    {
        return searchResultId;
    }

    public void setSearchResultId(Integer searchResultId)
    {
        this.searchResultId = searchResultId;
    }

    /*****searchSeqRc*****/
    @Column(name = "search_seq_rc")
    public String getSearchSeqRc()
    {
        return searchSeqRc;
    }

    public void setSearchSeqRc(String searchSeqRc)
    {
        this.searchSeqRc = searchSeqRc;
    }

    /*****resultSeq*****/
    @Column(name = "result_seq")
    public String getResultSeq()
    {
        return resultSeq;
    }

    public void setResultSeq(String resultSeq)
    {
        this.resultSeq = resultSeq;
    }

    /*****resultAccession*****/
    @Column(name = "result_accession")
    public String getResultAccession()
    {
        return resultAccession;
    }

    public void setResultAccession(String resultAccession)
    {
        this.resultAccession = resultAccession;
    }

    /*****resultAccessionOffset*****/
    @Column(name = "result_accession_offset")
    public Integer getResultAccessionOffset()
    {
        return resultAccessionOffset;
    }

    public void setResultAccessionOffset(Integer resultAccessionOffset)
    {
        this.resultAccessionOffset = resultAccessionOffset;
    }

    /*****resultOffset*****/
    @Column(name = "result_offset")
    public Integer getResultOffset()
    {
        return resultOffset;
    }

    public void setResultOffset(Integer resultOffset)
    {
        this.resultOffset = resultOffset;
    }

    /*****timeStamp*****/
    @Column(name = "time_stamp")
    public Date getTimeStamp()
    {
        return timeStamp;
    }

    public void setTimeStamp(Date timeStamp)
    {
        this.timeStamp = timeStamp;
    }

    public void setTimeStamp(String timeStamp)
    {
        try{
        DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
        formatter.setLenient(true);        this.timeStamp = formatter.parse(timeStamp);
        } catch (ParseException e) {e.printStackTrace();}
    }

    /*****searchStatus*****/
    @ManyToOne(fetch = FetchType.LAZY,  targetEntity=SearchStatus.class )
    @JoinColumn(name = "search_seq",nullable = true)
    public SearchStatus getSearchStatus()
    {
        return searchStatus;
    }

    public void setSearchStatus(SearchStatus searchStatus)
    {
        this.searchStatus = searchStatus;
    }


}
