package edu.uiowa.icts.safeseed.domain;

import java.util.Set;
import java.util.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.springframework.format.annotation.DateTimeFormat;
import org.hibernate.annotations.*;
import javax.persistence.CascadeType;
import edu.uiowa.icts.*;

/* Generated by Protogen - www.icts.uiowa.edu/protogen
 * @date 2011/03/03 16:15:53
*/ 

@Entity(name="edu_uiowa_icts_safeseed_domain_seq")
@Table(name = "seq", schema="safeseed")
public class Seq
{
        private Integer seqId;
        private String sequence;
        private String name;
        private String description;
        private String species;
        @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date dateAdded;
        private Set<GroupSeq> groupSeqs = new HashSet<GroupSeq>(0);
        private Set<SeqFrag> seqFrags = new HashSet<SeqFrag>(0);
        private Set<Submission> submissions = new HashSet<Submission>(0);
        private Set<SeqRelationship> seqRelationships = new HashSet<SeqRelationship>(0);
        private Set<Collection> collections = new HashSet<Collection>(0);
        private Person person;

    public Seq()    {
        this.seqId = 0;
        this.sequence = "";
        this.name = "";
        this.description = "";
        this.species = "";
        this.dateAdded = null;
        this.groupSeqs = new HashSet<GroupSeq>(0);
        this.seqFrags = new HashSet<SeqFrag>(0);
        this.submissions = new HashSet<Submission>(0);
        this.seqRelationships = new HashSet<SeqRelationship>(0);
        this.collections = new HashSet<Collection>(0);
        this.person = null;
    }

    public Seq(Integer seqId, String sequence, String name, String description, String species, Date dateAdded, Set<GroupSeq> groupSeqs, Set<SeqFrag> seqFrags, Set<Submission> submissions, Set<SeqRelationship> seqRelationships, Set<Collection> collections, Person person)
    {
        this.seqId = seqId;
        this.sequence = sequence;
        this.name = name;
        this.description = description;
        this.species = species;
        this.dateAdded = dateAdded;
        this.groupSeqs = groupSeqs;
        this.seqFrags = seqFrags;
        this.submissions = submissions;
        this.seqRelationships = seqRelationships;
        this.collections = collections;
        this.person = person;
    }

    /*****seqId*****/
    @javax.persistence.SequenceGenerator(  name="gen",  sequenceName="safeseed.seqnum",allocationSize=1)
    @Id
    @GeneratedValue( strategy=GenerationType.AUTO,generator="gen")
    @Column(name = "seq_id", unique = true, nullable = false)
    public Integer getSeqId()
    {
        return seqId;
    }

    public void setSeqId(Integer seqId)
    {
        this.seqId = seqId;
    }

    /*****sequence*****/
    @Column(name = "sequence")
    public String getSequence()
    {
        return sequence;
    }

    public void setSequence(String sequence)
    {
        this.sequence = sequence;
    }

    /*****name*****/
    @Column(name = "name")
    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    /*****description*****/
    @Column(name = "description")
    public String getDescription()
    {
        return description;
    }

    public void setDescription(String description)
    {
        this.description = description;
    }

    /*****species*****/
    @Column(name = "species")
    public String getSpecies()
    {
        return species;
    }

    public void setSpecies(String species)
    {
        this.species = species;
    }

    /*****dateAdded*****/
    @Column(name = "date_added")
    public Date getDateAdded()
    {
        return dateAdded;
    }

    public void setDateAdded(Date dateAdded)
    {
        this.dateAdded = dateAdded;
    }

    public void setDateAdded(String dateAdded)
    {
        try{
        DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
        formatter.setLenient(true);        this.dateAdded = formatter.parse(dateAdded);
        } catch (ParseException e) {e.printStackTrace();}
    }

    /*****groupSeqs*****/
    @OneToMany(fetch = FetchType.LAZY,   mappedBy = "seq", targetEntity=GroupSeq.class, cascade=CascadeType.REMOVE)
    public Set<GroupSeq> getGroupSeqs()
    {
        return groupSeqs;
    }

    public void setGroupSeqs(Set<GroupSeq> groupSeqs)
    {
        this.groupSeqs = groupSeqs;
    }

    /*****seqFrags*****/
    @OneToMany(fetch = FetchType.LAZY,   mappedBy = "seq", targetEntity=SeqFrag.class, cascade=CascadeType.REMOVE)
    public Set<SeqFrag> getSeqFrags()
    {
        return seqFrags;
    }

    public void setSeqFrags(Set<SeqFrag> seqFrags)
    {
        this.seqFrags = seqFrags;
    }

    /*****submissions*****/
    @OneToMany(fetch = FetchType.LAZY,   mappedBy = "seq", targetEntity=Submission.class, cascade=CascadeType.REMOVE)
    public Set<Submission> getSubmissions()
    {
        return submissions;
    }

    public void setSubmissions(Set<Submission> submissions)
    {
        this.submissions = submissions;
    }

    /*****seqRelationships*****/
    @OneToMany(fetch = FetchType.LAZY,   mappedBy = "seq", targetEntity=SeqRelationship.class, cascade=CascadeType.REMOVE)
    public Set<SeqRelationship> getSeqRelationships()
    {
        return seqRelationships;
    }

    public void setSeqRelationships(Set<SeqRelationship> seqRelationships)
    {
        this.seqRelationships = seqRelationships;
    }

    /*****collections*****/
    @OneToMany(fetch = FetchType.LAZY,   mappedBy = "seq", targetEntity=Collection.class, cascade=CascadeType.REMOVE)
    public Set<Collection> getCollections()
    {
        return collections;
    }

    public void setCollections(Set<Collection> collections)
    {
        this.collections = collections;
    }

    /*****person*****/
    @ManyToOne(fetch = FetchType.LAZY,  targetEntity=Person.class )
    @JoinColumn(name = "person_id",nullable = true)
    public Person getPerson()
    {
        return person;
    }

    public void setPerson(Person person)
    {
        this.person = person;
    }


}
