package edu.uiowa.icts.safeseed.domain;

import java.util.Set;
import java.util.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.springframework.format.annotation.DateTimeFormat;
import org.hibernate.annotations.*;
import javax.persistence.CascadeType;
import edu.uiowa.icts.*;

/* Generated by Protogen - www.icts.uiowa.edu/protogen
 * @date 2011/03/03 16:15:53
*/ 

@Entity(name="edu_uiowa_icts_safeseed_domain_seqFrag")
@Table(name = "seq_frag", schema="safeseed")
public class SeqFrag
{
        private Integer seqFragId;
        private Integer fragLength;
        private Boolean completed;
        private Set<Frag> frags = new HashSet<Frag>(0);
        private Set<Queue> queues = new HashSet<Queue>(0);
        private Set<Submission> submissions = new HashSet<Submission>(0);
        private Set<History> historys = new HashSet<History>(0);
        private Seq seq;

    public SeqFrag()    {
        this.seqFragId = null;
        this.fragLength = null;
        this.completed = null;
        this.frags = new HashSet<Frag>(0);
        this.queues = new HashSet<Queue>(0);
        this.submissions = new HashSet<Submission>(0);
        this.historys = new HashSet<History>(0);
        this.seq = null;
    }

    public SeqFrag(Integer seqFragId, Integer fragLength, Boolean completed, Set<Frag> frags, Set<Queue> queues, Set<Submission> submissions, Set<History> historys, Seq seq)
    {
        this.seqFragId = seqFragId;
        this.fragLength = fragLength;
        this.completed = completed;
        this.frags = frags;
        this.queues = queues;
        this.submissions = submissions;
        this.historys = historys;
        this.seq = seq;
    }

    /*****seqFragId*****/
    @javax.persistence.SequenceGenerator(  name="gen",  sequenceName="safeseed.seqnum",allocationSize=1)
    @Id
    @GeneratedValue( strategy=GenerationType.AUTO,generator="gen")
    @Column(name = "seq_frag_id", unique = true, nullable = false)
    public Integer getSeqFragId()
    {
        return seqFragId;
    }

    public void setSeqFragId(Integer seqFragId)
    {
        this.seqFragId = seqFragId;
    }

    /*****fragLength*****/
    @Column(name = "frag_length")
    public Integer getFragLength()
    {
        return fragLength;
    }

    public void setFragLength(Integer fragLength)
    {
        this.fragLength = fragLength;
    }

    /*****completed*****/
    @Column(name = "completed")
    public Boolean getCompleted()
    {
        return completed;
    }

    public void setCompleted(Boolean completed)
    {
        this.completed = completed;
    }

    /*****frags*****/
    @OneToMany(fetch = FetchType.LAZY,   mappedBy = "seqFrag", targetEntity=Frag.class, cascade=CascadeType.REMOVE)
    public Set<Frag> getFrags()
    {
        return frags;
    }

    public void setFrags(Set<Frag> frags)
    {
        this.frags = frags;
    }

    /*****queues*****/
    @OneToMany(fetch = FetchType.LAZY,   mappedBy = "seqFrag", targetEntity=Queue.class, cascade=CascadeType.REMOVE)
    public Set<Queue> getQueues()
    {
        return queues;
    }

    public void setQueues(Set<Queue> queues)
    {
        this.queues = queues;
    }

    /*****submissions*****/
    @OneToMany(fetch = FetchType.LAZY,   mappedBy = "seqFrag", targetEntity=Submission.class, cascade=CascadeType.REMOVE)
    public Set<Submission> getSubmissions()
    {
        return submissions;
    }

    public void setSubmissions(Set<Submission> submissions)
    {
        this.submissions = submissions;
    }

    /*****historys*****/
    @OneToMany(fetch = FetchType.LAZY,   mappedBy = "seqFrag", targetEntity=History.class, cascade=CascadeType.REMOVE)
    public Set<History> getHistorys()
    {
        return historys;
    }

    public void setHistorys(Set<History> historys)
    {
        this.historys = historys;
    }

    /*****seq*****/
    @ManyToOne(fetch = FetchType.LAZY,  targetEntity=Seq.class )
    @JoinColumn(name = "seq_id",nullable = true)
    public Seq getSeq()
    {
        return seq;
    }

    public void setSeq(Seq seq)
    {
        this.seq = seq;
    }


}
