package edu.uiowa.icts.safeseed.domain;

import java.util.Set;
import java.util.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.springframework.format.annotation.DateTimeFormat;
import org.hibernate.annotations.*;
import javax.persistence.CascadeType;
import edu.uiowa.icts.*;

/* Generated by Protogen - www.icts.uiowa.edu/protogen
 * @date 2011/03/03 16:15:53
*/ 

@Entity(name="edu_uiowa_icts_safeseed_domain_seqRelationship")
@Table(name = "seq_relationship", schema="safeseed")
public class SeqRelationship
{
        private SeqRelationshipId seqRelationshipId;
        private String note;
        private String type;
        private GlobalSeq globalSeq;
        private Seq seq;

    public SeqRelationship()    {
        this.seqRelationshipId = null;
        this.note = "";
        this.type = "";
        this.globalSeq = null;
        this.seq = null;
    }

    public SeqRelationship(SeqRelationshipId seqRelationshipId, String note, String type, GlobalSeq globalSeq, Seq seq)
    {
        this.seqRelationshipId = seqRelationshipId;
        this.note = note;
        this.type = type;
        this.globalSeq = globalSeq;
        this.seq = seq;
    }

    /*****seqRelationshipId*****/
    @EmbeddedId
    @AttributeOverrides( {

    @AttributeOverride(name = "seqId", column = @Column(name = "seq_id", nullable = false))
    ,
    @AttributeOverride(name = "globalSeqId", column = @Column(name = "global_seq_id", nullable = false))
    })
    public SeqRelationshipId getId()
    {
        return seqRelationshipId;
    }

    public void setId(SeqRelationshipId seqRelationshipId)
    {
        this.seqRelationshipId = seqRelationshipId;
    }

    /*****note*****/
    @Column(name = "note")
    public String getNote()
    {
        return note;
    }

    public void setNote(String note)
    {
        this.note = note;
    }

    /*****type*****/
    @Column(name = "type")
    public String getType()
    {
        return type;
    }

    public void setType(String type)
    {
        this.type = type;
    }

    /*****globalSeq*****/
    @ManyToOne(fetch = FetchType.LAZY,  targetEntity=GlobalSeq.class )
    @JoinColumn(name = "global_seq_id",nullable = false, insertable = false, updatable = false)
    public GlobalSeq getGlobalSeq()
    {
        return globalSeq;
    }

    public void setGlobalSeq(GlobalSeq globalSeq)
    {
        this.globalSeq = globalSeq;
    }

    /*****seq*****/
    @ManyToOne(fetch = FetchType.LAZY,  targetEntity=Seq.class )
    @JoinColumn(name = "seq_id",nullable = false, insertable = false, updatable = false)
    public Seq getSeq()
    {
        return seq;
    }

    public void setSeq(Seq seq)
    {
        this.seq = seq;
    }


}
