package edu.uiowa.icts.safeseed.domain;

import java.util.Set;
import java.util.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.springframework.format.annotation.DateTimeFormat;
import org.hibernate.annotations.*;
import javax.persistence.CascadeType;
import edu.uiowa.icts.*;

/* Generated by Protogen - www.icts.uiowa.edu/protogen
 * @date 2011/03/03 16:15:53
*/ 

@Entity(name="edu_uiowa_icts_safeseed_domain_systemSetting")
@Table(name = "system_setting", schema="safeseed")
public class SystemSetting
{
        private String systemSetting;
        private String value;
        private Boolean enabled;

    public SystemSetting()    {
        this.systemSetting = "";
        this.value = "";
        this.enabled = null;
    }

    public SystemSetting(String systemSetting, String value, Boolean enabled)
    {
        this.systemSetting = systemSetting;
        this.value = value;
        this.enabled = enabled;
    }

    /*****systemSetting*****/
    @Id
    @Column(name = "system_setting", unique = true, nullable = false)
    public String getSystemSetting()
    {
        return systemSetting;
    }

    public void setSystemSetting(String systemSetting)
    {
        this.systemSetting = systemSetting;
    }

    /*****value*****/
    @Column(name = "value")
    public String getValue()
    {
        return value;
    }

    public void setValue(String value)
    {
        this.value = value;
    }

    /*****enabled*****/
    @Column(name = "enabled")
    public Boolean getEnabled()
    {
        return enabled;
    }

    public void setEnabled(Boolean enabled)
    {
        this.enabled = enabled;
    }


}
