package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.spring.AbstractSpringTestCase;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;
import edu.uiowa.icts.safeseed.domain.*;

/* Generated by Protogen
 *
 * Unit test Template
*/


public class AuditTest extends AbstractSpringTestCase {


    @Autowired
    private SafeseedDaoService daoService;

    public SafeseedDaoService getDaoService()
    {
        return daoService;
    }

    public void setDaoService(SafeseedDaoService daoService)
    {
        this.daoService = daoService;
    }

    @Test
    public void testServiceName() {
    	assertEquals(true,true);
    	       
    }
    	   
    @Before
    public void setUp() throws Exception {
    	super.setUp();
    		   
    }
    	   
    @After
    public void tearDown() throws Exception {
    	super.tearDown();
    }

}
