package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/* Generated by Protogen
 *
 *
*/

@Repository("edu_uiowa_icts_safeseed_dao_AuditHome")
@Transactional
public class AuditHome extends GenericDao<Audit> implements AuditService {


    private static final Log log =LogFactory.getLog(AuditHome.class);

    public AuditHome()
    {        setDomainName("edu.uiowa.icts.safeseed.domain.Audit");

    }


    public Audit  findById(Integer id)

    {
        return (Audit)this.sessionFactory.getCurrentSession().get(getDomainName(), id);

    }




}
