package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;

/* Generated by Protogen
 *
 *
*/


public interface AuditService extends GenericDaoInterface<Audit> {


    public Audit  findById(Integer id);

}
