package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/* Generated by Protogen
 *
 *
*/

@Repository("edu_uiowa_icts_safeseed_dao_CollectionHome")
@Transactional
public class CollectionHome extends GenericDao<Collection> implements CollectionService {


    private static final Log log =LogFactory.getLog(CollectionHome.class);

    public CollectionHome()
    {        setDomainName("edu.uiowa.icts.safeseed.domain.Collection");

    }


    public Collection  findById(CollectionId id)

    {
        return (Collection)this.sessionFactory.getCurrentSession().get(getDomainName(), id);

    }




}
