package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;

/* Generated by Protogen
 *
 *
*/


public interface CollectionService extends GenericDaoInterface<Collection> {


    public Collection  findById(CollectionId id);

}
