package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;

/* Generated by Protogen
 *
 *
*/


public interface FragService extends GenericDaoInterface<Frag> {


    public Frag  findById(Integer id);

}
