package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;

/* Generated by Protogen
 *
 *
*/


public interface GlobalFragService extends GenericDaoInterface<GlobalFrag> {


    public GlobalFrag  findById(Integer id);

}
