package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/* Generated by Protogen
 *
 *
*/

@Repository("edu_uiowa_icts_safeseed_dao_GlobalHistoryHome")
@Transactional
public class GlobalHistoryHome extends GenericDao<GlobalHistory> implements GlobalHistoryService {


    private static final Log log =LogFactory.getLog(GlobalHistoryHome.class);

    public GlobalHistoryHome()
    {        setDomainName("edu.uiowa.icts.safeseed.domain.GlobalHistory");

    }


    public GlobalHistory  findById(Integer id)

    {
        return (GlobalHistory)this.sessionFactory.getCurrentSession().get(getDomainName(), id);

    }




}
