package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;

/* Generated by Protogen
 *
 *
*/


public interface GlobalSeqService extends GenericDaoInterface<GlobalSeq> {


    public GlobalSeq  findById(Integer id);

}
