package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/* Generated by Protogen
 *
 *
*/

@Repository("edu_uiowa_icts_safeseed_dao_GlobalFragHome")
@Transactional
public class GlobalFragHome extends GenericDao<GlobalFrag> implements GlobalFragService {


    private static final Log log =LogFactory.getLog(GlobalFragHome.class);

    public GlobalFragHome()
    {        setDomainName("edu.uiowa.icts.safeseed.domain.GlobalFrag");

    }


    public GlobalFrag  findById(Integer id)

    {
        return (GlobalFrag)this.sessionFactory.getCurrentSession().get(getDomainName(), id);

    }




}
