package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/* Generated by Protogen
 *
 *
*/

@Repository("edu_uiowa_icts_safeseed_dao_GlobalSeqHome")
@Transactional
public class GlobalSeqHome extends GenericDao<GlobalSeq> implements GlobalSeqService {


    private static final Log log =LogFactory.getLog(GlobalSeqHome.class);

    public GlobalSeqHome()
    {        setDomainName("edu.uiowa.icts.safeseed.domain.GlobalSeq");

    }


    public GlobalSeq  findById(Integer id)

    {
        return (GlobalSeq)this.sessionFactory.getCurrentSession().get(getDomainName(), id);

    }




}
