package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;

/* Generated by Protogen
 *
 *
*/


public interface GlobalCollectionService extends GenericDaoInterface<GlobalCollection> {


    public GlobalCollection  findById(Integer id);

}
