package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;

/* Generated by Protogen
 *
 *
*/


public interface GlobalHistoryService extends GenericDaoInterface<GlobalHistory> {


    public GlobalHistory  findById(Integer id);

}
