package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;

/* Generated by Protogen
 *
 *
*/


public interface GroupSeqService extends GenericDaoInterface<GroupSeq> {


    public GroupSeq  findById(GroupSeqId id);

}
