package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/* Generated by Protogen
 *
 *
*/

@Repository("edu_uiowa_icts_safeseed_dao_GroupGlobalSeqHome")
@Transactional
public class GroupGlobalSeqHome extends GenericDao<GroupGlobalSeq> implements GroupGlobalSeqService {


    private static final Log log =LogFactory.getLog(GroupGlobalSeqHome.class);

    public GroupGlobalSeqHome()
    {        setDomainName("edu.uiowa.icts.safeseed.domain.GroupGlobalSeq");

    }


    public GroupGlobalSeq  findById(GroupGlobalSeqId id)

    {
        return (GroupGlobalSeq)this.sessionFactory.getCurrentSession().get(getDomainName(), id);

    }




}
