package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/* Generated by Protogen
 *
 *
*/

@Repository("edu_uiowa_icts_safeseed_dao_GroupHome")
@Transactional
public class GroupHome extends GenericDao<Group> implements GroupService {


    private static final Log log =LogFactory.getLog(GroupHome.class);

    public GroupHome()
    {        setDomainName("edu.uiowa.icts.safeseed.domain.Group");

    }


    public Group  findById(Integer id)

    {
        return (Group)this.sessionFactory.getCurrentSession().get(getDomainName(), id);

    }




}
