package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;

/* Generated by Protogen
 *
 *
*/


public interface GroupService extends GenericDaoInterface<Group> {


    public Group  findById(Integer id);

}
