package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/* Generated by Protogen
 *
 *
*/

@Repository("edu_uiowa_icts_safeseed_dao_HistoryHome")
@Transactional
public class HistoryHome extends GenericDao<History> implements HistoryService {


    private static final Log log =LogFactory.getLog(HistoryHome.class);

    public HistoryHome()
    {        setDomainName("edu.uiowa.icts.safeseed.domain.History");

    }


    public History  findById(Integer id)

    {
        return (History)this.sessionFactory.getCurrentSession().get(getDomainName(), id);

    }




}
