package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/* Generated by Protogen
 *
 *
*/

@Repository("edu_uiowa_icts_safeseed_dao_PersonGroupHome")
@Transactional
public class PersonGroupHome extends GenericDao<PersonGroup> implements PersonGroupService {


    private static final Log log =LogFactory.getLog(PersonGroupHome.class);

    public PersonGroupHome()
    {        setDomainName("edu.uiowa.icts.safeseed.domain.PersonGroup");

    }


    public PersonGroup  findById(PersonGroupId id)

    {
        return (PersonGroup)this.sessionFactory.getCurrentSession().get(getDomainName(), id);

    }




}
