package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.hibernate.Query;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/* Generated by Protogen
 *
 *
*/

@Repository("edu_uiowa_icts_safeseed_dao_PersonHome")
@Transactional
public class PersonHome extends GenericDao<Person> implements PersonService {


    private static final Log log =LogFactory.getLog(PersonHome.class);

    public PersonHome()
    {        setDomainName("edu.uiowa.icts.safeseed.domain.Person");

    }


    public Person  findById(Integer id)

    {
        return (Person)this.sessionFactory.getCurrentSession().get(getDomainName(), id);

    }
    public Person  findByUsername(String username)

    {
    	String qString = "Select p from "+getDomainName()+" as p WHERE p.username = ?";
        Query q = this.sessionFactory.getCurrentSession().createQuery(qString);
        q.setString(0, username);
        return (Person)q.uniqueResult();

    }


    
    public Person  findByEmail(String email)

    {
    	String qString = "Select p from "+getDomainName()+" as p WHERE p.email = ?";
        Query q = this.sessionFactory.getCurrentSession().createQuery(qString);
        q.setString(0, email);
        return (Person)q.uniqueResult();

    }




}
