package edu.uiowa.icts.safeseed.dao;

import java.util.List;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.hibernate.Query;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/* Generated by Protogen
 *
 *
*/

@Repository("edu_uiowa_icts_safeseed_dao_QueueHome")
@Transactional
public class QueueHome extends GenericDao<Queue> implements QueueService {


    private static final Log log =LogFactory.getLog(QueueHome.class);

    public QueueHome()
    {        setDomainName("edu.uiowa.icts.safeseed.domain.Queue");

    }


    public Queue  findById(Integer id)

    {
        return (Queue)this.sessionFactory.getCurrentSession().get(getDomainName(), id);

    }
    
    
    public Queue  getNext()

    {
    	
    	String qString = "Select q from " + getDomainName() + " as q WHERE q.complete=false order by q.priorityLevel ASC, q.queueId ASC";
    	Query q = this.sessionFactory.getCurrentSession().createQuery(qString);
    	
    	List<Object> list = q.list();
    	if(list !=null && list.size()>0)
    		return (Queue)list.iterator().next();
    	
        return null;

    }




}
