package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/* Generated by Protogen
 *
 *
*/

@Repository("edu_uiowa_icts_safeseed_dao_SearchResultHome")
@Transactional
public class SearchResultHome extends GenericDao<SearchResult> implements SearchResultService {


    private static final Log log =LogFactory.getLog(SearchResultHome.class);

    public SearchResultHome()
    {        setDomainName("edu.uiowa.icts.safeseed.domain.SearchResult");

    }


    public SearchResult  findById(Integer id)

    {
        return (SearchResult)this.sessionFactory.getCurrentSession().get(getDomainName(), id);

    }




}
