package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/* Generated by Protogen
 *
 *
*/

@Repository("edu_uiowa_icts_safeseed_dao_SearchStatusHome")
@Transactional
public class SearchStatusHome extends GenericDao<SearchStatus> implements SearchStatusService {


    private static final Log log =LogFactory.getLog(SearchStatusHome.class);

    public SearchStatusHome()
    {        setDomainName("edu.uiowa.icts.safeseed.domain.SearchStatus");

    }


    public SearchStatus  findById(String id)

    {
        return (SearchStatus)this.sessionFactory.getCurrentSession().get(getDomainName(), id);

    }




}
