package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;

/* Generated by Protogen
 *
 *
*/


public interface SearchResultService extends GenericDaoInterface<SearchResult> {


    public SearchResult  findById(Integer id);

}
