package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/* Generated by Protogen
 *
 *
*/

@Repository("edu_uiowa_icts_safeseed_dao_SeqFragHome")
@Transactional
public class SeqFragHome extends GenericDao<SeqFrag> implements SeqFragService {


    private static final Log log =LogFactory.getLog(SeqFragHome.class);

    public SeqFragHome()
    {        setDomainName("edu.uiowa.icts.safeseed.domain.SeqFrag");

    }


    public SeqFrag  findById(Integer id)

    {
        return (SeqFrag)this.sessionFactory.getCurrentSession().get(getDomainName(), id);

    }




}
