package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;

/* Generated by Protogen
 *
 *
*/


public interface SeqFragService extends GenericDaoInterface<SeqFrag> {


    public SeqFrag  findById(Integer id);

}
