package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;

/* Generated by Protogen
 *
 *
*/


public interface SeqService extends GenericDaoInterface<Seq> {


    public Seq  findById(Integer id);

}
