package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.hibernate.Query;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/* Generated by Protogen
 *
 *
*/

@Repository("edu_uiowa_icts_safeseed_dao_SiteContentHome")
@Transactional
public class SiteContentHome extends GenericDao<SiteContent> implements SiteContentService {


    private static final Log log =LogFactory.getLog(SiteContentHome.class);

    public SiteContentHome()
    {        setDomainName("edu.uiowa.icts.safeseed.domain.SiteContent");

    }


    public SiteContent  findById(Integer id)

    {
        return (SiteContent)this.sessionFactory.getCurrentSession().get(getDomainName(), id);

    }
    public SiteContent  findByLabel(String label)

    {
    	String qString = "Select c from "+getDomainName()+" as c WHERE c.label = ?";
        Query q = this.sessionFactory.getCurrentSession().createQuery(qString);
        q.setString(0, label);
        return (SiteContent)q.uniqueResult();

    }






}
