package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;

/* Generated by Protogen
 *
 *
*/


public interface SubmissionService extends GenericDaoInterface<Submission> {


    public Submission  findById(Integer id);

}
