package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;

/* Generated by Protogen
 *
 *
*/


public interface SystemSettingService extends GenericDaoInterface<SystemSetting> {


    public SystemSetting  findById(String id);

}
