package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.safeseed.domain.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/* Generated by Protogen
 *
 *
*/

@Repository("edu_uiowa_icts_safeseed_dao_SystemSettingHome")
@Transactional
public class SystemSettingHome extends GenericDao<SystemSetting> implements SystemSettingService {


    private static final Log log =LogFactory.getLog(SystemSettingHome.class);

    public SystemSettingHome()
    {        setDomainName("edu.uiowa.icts.safeseed.domain.SystemSetting");

    }


    public SystemSetting  findById(String id)

    {
        return (SystemSetting)this.sessionFactory.getCurrentSession().get(getDomainName(), id);

    }




}
